package main

// Boundary audit — ported from tools/audit-boundary.mjs.
//
// Categorizes every file in the repo as PROGRAMMATIC (regenerated by tools on
// `make build`) vs TOOL SOURCE (hand-written code that owns those outputs) vs
// HAND-AUTHORED (LLM/human content that no script owns), and surfaces the
// explicit LLM PATCH POINTS inside tool source.
//
//	pipeline audit-boundary            human-readable report; exit 0 always
//	pipeline audit-boundary --strict   JSON to stdout, exit 1 on drift
//	pipeline audit-boundary discover   new files + a suggested pattern for each
//
// The path patterns ARE the source of truth — each one documents which tool
// owns the output and what it generates from. To extend, add a pattern below
// with the owning tool and source reference.
//
// Patterns are matched first-match-wins and the order is load-bearing: a
// catch-all placed before a specific rule shadows it. That is a real bug this
// file already carried once (a dist/components RTL file was attributed to the
// emitter instead of build-rtl), so the ordering is asserted by a test rather
// than left to reading.

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
)

// A classification pattern. Exactly one of tool/note/owner is set, matching
// the three kinds.
type boundaryPattern struct {
	re     *regexp.Regexp
	match  func(string) bool // used when the rule is not a plain regex
	tool   string            // programmatic: what regenerates it
	source string            // programmatic: what it is generated from
	note   string            // tool-source: what this code owns
	owner  string            // hand-authored: who maintains it
}

func (p boundaryPattern) test(path string) bool {
	if p.match != nil {
		return p.match(path)
	}
	return p.re.MatchString(path)
}

func re(s string) *regexp.Regexp { return regexp.MustCompile(s) }

// hasPrefixAnd is the common shape: a directory prefix plus a suffix test.
func prefixSuffix(prefix string, suffixes ...string) func(string) bool {
	return func(p string) bool {
		if !strings.HasPrefix(p, prefix) {
			return false
		}
		if len(suffixes) == 0 {
			return true
		}
		for _, s := range suffixes {
			if strings.HasSuffix(p, s) {
				return true
			}
		}
		return false
	}
}

func oneOf(paths ...string) func(string) bool {
	set := map[string]bool{}
	for _, p := range paths {
		set[p] = true
	}
	return func(p string) bool { return set[p] }
}

var reRtlVariant = re(`-rtl-(en|he|fa)\.html$`)

var toolSourcePatterns = []boundaryPattern{
	{re: re(`^pipeline/.*\.go$`),
		note: "pipeline/*.go — the Go runner + the ported builder tools (resolve-skins, rtl-dict, build-rtl, demo, docs-consistency, docs-catalog, product-css, build-js)"},
	{re: re(`^tools/.*\.mjs$`),
		note: "tools/*.mjs — remaining JS builder tools + gates (docs-build, example-*, oracle, style-parity, …)"},
	{re: re(`^src/converter/.*\.mjs$`),
		note: "src/converter/*.mjs — registry .tsx → IR JSON (src/registry/ir/*.json)"},
	{re: re(`^src/emitter/.*\.mjs$`),
		note: "src/emitter/*.mjs — IR JSON → dist/components/*.html + slot CSS"},
	{re: re(`^src/docs/.*\.mjs$`),
		note: "src/docs/*.mjs — JSX/runtime used by the MDX compile step (ComponentPreview, code-copy/view-code/rtl handlers, theme pre-paint, etc.)"},
	{re: re(`^src/runtime/.*\.(mjs|js)$`),
		note: "src/runtime/*.mjs|js — interactive runtime copied into dist/ as shadless.js"},
	{match: oneOf("src/tags.mjs"),
		note: "src/tags.mjs — tag normalization shared by converter/emitter/css"},
}

var programmaticPatterns = []boundaryPattern{
	// IR (converter)
	{match: func(p string) bool {
		return strings.HasPrefix(p, "src/registry/ir/") && strings.HasSuffix(p, ".json")
	},
		tool: "src/converter/index.mjs", source: "apps/v4/registry/bases/radix/ui/*.tsx"},
	// dist/components — emitter + build-rtl + demo (multi-source)
	{match: func(p string) bool {
		return strings.HasPrefix(p, "dist/components/") && strings.HasSuffix(p, ".html") &&
			!reRtlVariant.MatchString(p) && !strings.HasSuffix(p, "-demo.html")
	},
		tool:   "src/emitter/index.mjs OR pipeline/demo.go (per-tier fixture)",
		source: "src/registry/ir/*.json + probes/t{6,7,8,9}/* (per tier)"},
	{match: func(p string) bool {
		return strings.HasPrefix(p, "dist/components/") && reRtlVariant.MatchString(p)
	},
		tool: "pipeline/build_rtl.go", source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/rtl_dict.go)"},
	// docs/demos — build-rtl writes here too (so the host page can serve the
	// iframes even before docs-build copies them into docs/site/).
	{match: func(p string) bool {
		return strings.HasPrefix(p, "docs/demos/") && reRtlVariant.MatchString(p)
	},
		tool: "pipeline/build_rtl.go", source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/rtl_dict.go)"},
	// The rest of docs/demos was classified as hand-authored, and 331 of the
	// 429 files are not: example-oracle renders each upstream example with
	// React and writes the page, and example-fixture wires the ones carrying a
	// kernel family. Both record what they wrote, so ownership is read from
	// those manifests rather than guessed from the path — a guess is what got
	// this wrong, and it made the boundary audit claim no tool owned files a
	// tool had just written.
	{match: inManifest("docs/example-fixture-targets.json", "name"),
		tool:   "tools/example-fixture.mjs",
		source: "the React oracle render, with kernel-family JS wired in"},
	{match: inManifest("docs/example-oracle.json", "out"),
		tool:   "tools/example-oracle.mjs",
		source: "examples/radix/<name>.tsx, rendered with real React"},
	// dist CSS / JS — tailwind + copy
	{match: oneOf("dist/out.css", "dist/globals.css", "dist/shadless.css", "dist/shadless-core.css"),
		tool:   "npx @tailwindcss/cli (via make demo / make docs)",
		source: "dist/components/*.html + shadless CSS fixes"},
	// J2 product surface — per-component @apply sources + tokens + compiled
	{match: prefixSuffix("dist/css/", ".css"),
		tool:   "pipeline/demo.go (parts) + pipeline/product_css.go (tokens)",
		source: "src/registry/ir/*.json + probes/h4/globals.css"},
	{match: oneOf("dist/shadless.product.css", "dist/shadless.full.css", "dist/shadless.full.min.css"),
		tool:   "pipeline/product_css.go + pipeline/tw.go",
		source: "dist/css/* (tokens + component parts + fixes)"},
	// J4: server-stack template macros — regenerated from IR
	{match: oneOf("dist/shadless.js", "dist/shadless.min.js"),
		tool: "tools/build-js.mjs", source: "vendor/radix-kernel.iife.js + src/runtime/core.js"},
	{match: func(p string) bool {
		return (strings.HasPrefix(p, "dist/js/") || strings.HasPrefix(p, "dist/esm/")) &&
			re(`\.(m?js|d\.ts)$`).MatchString(p)
	},
		tool:   "tools/build-js.mjs",
		source: "src/runtime/core.js + src/runtime/components/*.js + src/runtime/shadless.d.ts + vendor/*.iife.js"},
	{match: oneOf("dist/demo-index.html"),
		tool: "pipeline/demo.go", source: "per-tier IR list (built into demo.mjs)"},
	// docs/site — docs-build output
	{match: prefixSuffix("docs/site/", ".html", ".css", ".js"),
		tool:   "tools/docs-build.mjs",
		source: "apps/v4/content/docs/components/*/*.mdx (compiled via MDX)"},
	{match: oneOf("build/rtl-langs.json"),
		tool: "pipeline/build_rtl.go", source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/rtl_dict.go)"},
	// catalog + reports
	{match: oneOf("docs/catalog.json"),
		tool:   "pipeline/docs_catalog.go",
		source: ".upstream/.../components/*/*.mdx + dist/components state"},
	// (patches/ overlay retired — manual interventions live in overlays/ + src/)
}

var handAuthoredPatterns = []boundaryPattern{
	// Vendor files (vendored from upstream release artifacts)
	{match: oneOf("vendor/radix-kernel.iife.js"), owner: "human (vendor)"},
	{match: oneOf("vendor/embla-carousel.iife.js"), owner: "human (vendor)"},
	// what neither manifest claims: the examples no oracle can bundle
	// (external deps, recorded in the golden exemptions)
	{match: func(p string) bool {
		return strings.HasPrefix(p, "docs/demos/") && !strings.Contains(p, "-rtl")
	},
		owner: "human (examples the oracle cannot bundle — see the golden exemptions)"},
	// Guide source content (consumed by docs-build)
	{match: prefixSuffix("docs/content/", ".mdx"),
		owner: "human (guide source — compiled by docs-build into docs/site/)"},
	{match: oneOf("docs/content-map.json"), owner: "human (FT7 build state)"},
	// Pin tracking
	{match: oneOf("src/registry/pin.json"),
		owner: "pipeline upstream (re-pin) / human (vendor re-hash via ./build/pipeline pin --force)"},
	// Docs / orchestration (mix of programmatic generation and human prose)
	{match: func(p string) bool {
		switch p {
		case "Makefile", "README.md", "UPGRADING.md", "package.json", ".gitignore", "package-lock.json":
			return true
		}
		return re(`^FINDING-.*\.md$`).MatchString(p)
	},
		owner: "human (orchestration + narrative)"},
	// Probe fixtures — used by emit/demo as references, but hand-written
	{match: prefixSuffix("probes/"),
		owner: "human (test fixtures; some consumed by pipeline/demo.go)"},
}

// llmPatchPoint is a curated region inside tool source where a human is
// expected to intervene. Not regenerated — the seam between script and human.
type llmPatchPoint struct{ File, Lines, What string }

var llmPatchPoints = []llmPatchPoint{
	{"pipeline/build_rtl.go", "32-37",
		"PERSIAN translations dict — 4 keys × 2 alerts for alert-rtl only. Upstream ships en/ar/he; Persian isn't in upstream so hand-coded. When upstream adds a new language, add it here (or generalize to read from upstream)."},
	{"pipeline/demo.go", "~127-230",
		"Per-tier HTML fixtures (dialogDemoHtml, fieldDemoHtml, etc.) — kernel/trivial-js components get static HTML hand-written here; consumed by pipeline/demo.go."},
	{"docs/demos/", "(directory)",
		"Almost all of this is generated: example-oracle writes 226 pages from the React render, example-fixture 105 more with kernel-family JS wired in, build-rtl the *-rtl-{he,en,fa} variants. What is left hand-authored is the message-scroller family, whose examples the oracle cannot bundle (external deps) and which is recorded in the golden exemptions and in interactivity-sweep's KNOWN_DEAD."},
}

// ---------------------------------------------------------------- scan

type classification struct {
	Path   string
	Kind   string // programmatic | tool-source | hand-authored | unknown
	Tool   string
	Source string
	Note   string
	Owner  string
}

// label is the grouping key for a classification: the tool that owns it, the
// note describing it, or its owner.
func (c classification) label() string {
	switch {
	case c.Tool != "":
		return c.Tool
	case c.Note != "":
		return c.Note
	case c.Owner != "":
		return c.Owner
	}
	return ""
}

func classifyPath(path string) classification {
	for _, p := range programmaticPatterns {
		if p.test(path) {
			return classification{Path: path, Kind: "programmatic", Tool: p.tool, Source: p.source}
		}
	}
	for _, p := range toolSourcePatterns {
		if p.test(path) {
			return classification{Path: path, Kind: "tool-source", Note: p.note}
		}
	}
	for _, p := range handAuthoredPatterns {
		if p.test(path) {
			return classification{Path: path, Kind: "hand-authored", Owner: p.owner}
		}
	}
	return classification{Path: path, Kind: "unknown"}
}

// auditSkip: dist/ is deliberately NOT skipped — dist/components/*.html is
// git-tracked and is the live library output. tools/contracts/out IS skipped:
// those are runtime oracle artifacts, not repo source.
var auditSkip = []string{".git", "node_modules", ".upstream", "tools/contracts/out"}

func auditWalk(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return nil // an unreadable directory is skipped, as readdirSync's catch did
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil || rel == "." {
			return nil
		}
		if auditShouldSkip(rel) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if !d.IsDir() {
			out = append(out, rel)
		}
		return nil
	})
	sort.Strings(out)
	return out, err
}

func auditShouldSkip(rel string) bool {
	for _, s := range auditSkip {
		if strings.Contains(s, "/") {
			// path-prefix match
			if rel == s || strings.HasPrefix(rel, s+"/") {
				return true
			}
			continue
		}
		for _, seg := range strings.Split(rel, "/") {
			if seg == s {
				return true
			}
		}
	}
	return false
}

// ------------------------------------------------------- drift detection

// detectDrift finds tool-generated files MODIFIED relative to HEAD. Untracked
// files are NOT drift: they are the normal state after `make build`. Only a
// file someone touched after the tool generated it counts.
func detectDrift(root string, programmatic []classification) []classification {
	modified := gitPaths(root, "--untracked-files=no", func(x, y byte) bool {
		return x == 'M' || y == 'M' || x == 'D' || y == 'D'
	})
	var out []classification
	for _, c := range programmatic {
		if modified[c.Path] {
			out = append(out, c)
		}
	}
	return out
}

// gitPaths runs git status --porcelain and returns the paths whose XY status
// satisfies keep. A git that is not available yields nothing, as the JS did.
func gitPaths(root, untracked string, keep func(x, y byte) bool) map[string]bool {
	out := map[string]bool{}
	cmd := exec.Command("git", "status", "--porcelain", untracked)
	cmd.Dir = root
	b, err := cmd.Output()
	if err != nil {
		return out
	}
	for _, line := range strings.Split(string(b), "\n") {
		if len(line) < 4 {
			continue
		}
		if !keep(line[0], line[1]) {
			continue
		}
		rest := line[3:]
		if i := strings.Index(rest, " -> "); i >= 0 {
			rest = rest[i+4:] // a rename reports the destination
		}
		out[strings.Trim(rest, `"`)] = true
	}
	return out
}

// detectNewFiles lists untracked and staged-added paths — everything new
// since HEAD.
func detectNewFiles(root string) []string {
	paths := gitPaths(root, "--untracked-files=all", func(x, y byte) bool {
		return (x == '?' && y == '?') || x == 'A'
	})
	var out []string
	for p := range paths {
		if strings.HasSuffix(p, "/") {
			continue // git lists directories with a trailing slash
		}
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

// ------------------------------------------------------- discover mode

// heuristicHint suggests a pattern for a path nothing matched. SPECIFIC rules
// come first: the dist/ catch-all below shadows anything placed after it, and
// a dist/components RTL file was once suggested as "emitter OR demo" instead
// of build-rtl for exactly that reason.
type heuristicHint struct {
	re                 *regexp.Regexp
	kind, tool, source string
	note, owner        string
}

var heuristicHints = []heuristicHint{
	{re: re(`^dist/components/[^/]+-rtl-(en|he|fa)\.html$`),
		kind: "programmatic", tool: "pipeline/build_rtl.go", source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/rtl_dict.go)"},
	{re: re(`^docs/demos/[^/]+-rtl-(en|he|fa)\.html$`),
		kind: "programmatic", tool: "pipeline/build_rtl.go", source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/rtl_dict.go)"},
	{re: re(`^(docs/demos|dist/components)/[^/]+-demo\.html$`),
		kind: "programmatic", tool: "tools/example-oracle.mjs", source: "examples/radix/<name>-demo.tsx, rendered with real React"},
	{re: re(`^dist/glue/`),
		kind: "programmatic", tool: "pipeline/demo.go", source: "src/kernel/*-glue.js"},
	// Catch-all: any HTML under dist/ is a build artifact. The specific rules
	// above catch the known subdirs; this handles a new one (dist/widgets/)
	// that nobody has added a rule for yet.
	{re: re(`^dist/.+\.html$`),
		kind: "programmatic", tool: "src/emitter/index.mjs OR pipeline/demo.go (per-tier fixture)",
		source: "src/registry/ir/*.json + probes/t{6,7,8,9}/*"},
	{re: re(`^docs/site/[^/]+\.html$`),
		kind: "programmatic", tool: "tools/docs-build.mjs", source: "apps/v4/content/docs/components/*/*.mdx"},
	{re: re(`^src/registry/ir/[^/]+\.json$`),
		kind: "programmatic", tool: "src/converter/index.mjs", source: "apps/v4/registry/bases/radix/ui/*.tsx"},
	{re: re(`^tools/[^/]+\.mjs$`),
		kind: "tool-source", note: "pipeline orchestrator + builder tool"},
	{re: re(`^scripts/[^/]+\.(sh|js|mjs)$`),
		kind: "tool-source", note: "scripts/*.sh|js|mjs — ad-hoc scripts; consider promoting to tools/ if used by Makefile"},
	{re: re(`^src/converter/[^/]+\.mjs$`),
		kind: "tool-source", note: "src/converter — registry → IR"},
	{re: re(`^src/emitter/[^/]+\.mjs$`),
		kind: "tool-source", note: "src/emitter — IR → dist/components + slot CSS"},
	{re: re(`^src/docs/[^/]+\.mjs$`),
		kind: "tool-source", note: "src/docs — JSX runtime used by MDX compile"},
	{re: re(`^src/runtime/[^/]+\.(mjs|js)$`),
		kind: "tool-source", note: "src/runtime — interactive runtime (copied to dist/shadless.js)"},
	{re: re(`^vendor/`),
		kind: "hand-authored", owner: "human (vendor — manually vendored from upstream)"},
	{re: re(`^probes/`),
		kind: "hand-authored", owner: "human (test fixture)"},
	{re: re(`^docs/demos/`),
		kind: "hand-authored", owner: "human (remaining hand-written demos only — all programmatic demos come from example-oracle)"},
	{re: re(`^docs/content/[^/]+\.mdx$`),
		kind: "hand-authored", owner: "human (guide source — compiled by docs-build)"},
	{re: re(`^src/registry/pin\.json$`),
		kind: "hand-authored", owner: "human (commit hash + vendor SHA256)"},
}

type suggestion struct {
	Method     string
	Confidence float64
	Kind       string
	Tool       string
	Source     string
	Note       string
	Owner      string
	Sampled    int
	Total      int
}

// suggestFromSiblings looks at files in the SAME DIRECTORY (not the whole
// subtree — that would overweight huge dirs like docs/site/) that already
// match a pattern, and proposes the dominant category.
func suggestFromSiblings(newPath string, all []string, byPath map[string]classification) *suggestion {
	dir := parentDir(newPath)
	var siblings, matched []classification
	for _, p := range all {
		if p == newPath || parentDir(p) != dir {
			continue
		}
		c := byPath[p]
		siblings = append(siblings, c)
		if c.Kind != "" && c.Kind != "unknown" {
			matched = append(matched, c)
		}
	}
	if len(matched) == 0 {
		return nil
	}
	type key struct{ kind, label string }
	counts := map[key]int{}
	for _, m := range matched {
		counts[key{m.Kind, m.label()}]++
	}
	// deterministic winner: highest count, then lexical
	var best key
	bestN := -1
	var keys []key
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].kind != keys[j].kind {
			return keys[i].kind < keys[j].kind
		}
		return keys[i].label < keys[j].label
	})
	for _, k := range keys {
		if counts[k] > bestN {
			best, bestN = k, counts[k]
		}
	}
	s := &suggestion{
		Method: "sibling", Kind: best.kind,
		Confidence: float64(bestN) / float64(len(siblings)),
		Sampled:    len(matched), Total: len(siblings),
	}
	switch best.kind {
	case "programmatic":
		s.Tool = best.label
	case "tool-source":
		s.Note = best.label
	case "hand-authored":
		s.Owner = best.label
	}
	return s
}

func parentDir(p string) string {
	if i := strings.LastIndex(p, "/"); i >= 0 {
		return p[:i+1]
	}
	return ""
}

func suggestFromHeuristics(newPath string) *suggestion {
	for _, h := range heuristicHints {
		if h.re.MatchString(newPath) {
			return &suggestion{Method: "heuristic", Confidence: 0.8, Kind: h.kind,
				Tool: h.tool, Source: h.source, Note: h.note, Owner: h.owner}
		}
	}
	return nil
}

func runDiscoverMode(root string, all []string, byPath map[string]classification) {
	newFiles := detectNewFiles(root)
	if len(newFiles) == 0 {
		fmt.Println("No new files detected in git working tree.")
		return
	}
	fmt.Printf("Discovered %d new file%s (untracked + added since HEAD):\n\n",
		len(newFiles), plural(len(newFiles)))
	var matched []classification
	var unmatched []string
	for _, p := range newFiles {
		if c, ok := byPath[p]; ok && c.Kind != "unknown" {
			matched = append(matched, c)
			continue
		}
		unmatched = append(unmatched, p)
	}
	if len(matched) > 0 {
		fmt.Println("ALREADY CLASSIFIED (matches existing pattern)")
		fmt.Println(strings.Repeat("-", 72))
		for _, m := range matched {
			fmt.Printf("  [%s] %s\n", m.Kind, m.Path)
		}
		fmt.Println()
	}
	if len(unmatched) == 0 {
		return
	}
	fmt.Println("UNCLASSIFIED (needs a new pattern)")
	fmt.Println(strings.Repeat("-", 72))
	type row struct {
		path             string
		sibling, heurist *suggestion
	}
	var rows []row
	for _, p := range unmatched {
		rows = append(rows, row{p, suggestFromSiblings(p, all, byPath), suggestFromHeuristics(p)})
	}
	for _, r := range rows {
		fmt.Printf("  %s\n", r.path)
		if s := r.sibling; s != nil {
			fmt.Printf("    sibling-based: %d%% confidence (%d siblings match)\n",
				int(s.Confidence*100+0.5), s.Sampled)
			fmt.Printf("      kind:  %s\n", s.Kind)
			printIf("      tool:  %s\n", s.Tool)
			printIf("      note:  %s\n", s.Note)
			printIf("      owner: %s\n", s.Owner)
		}
		if s := r.heurist; s != nil {
			fmt.Printf("    heuristic: %d%% confidence\n", int(s.Confidence*100+0.5))
			fmt.Printf("      kind:  %s\n", s.Kind)
			printIf("      tool:  %s\n", s.Tool)
			printIf("      source: %s\n", s.Source)
			printIf("      note:  %s\n", s.Note)
			printIf("      owner: %s\n", s.Owner)
		}
		if r.sibling == nil && r.heurist == nil {
			fmt.Println("    NO SUGGESTION — needs manual categorization")
		}
		fmt.Println()
	}
	fmt.Println("SUGGESTED PATTERN ADDITIONS (copy-paste into pipeline/audit_boundary.go):")
	fmt.Println(strings.Repeat("-", 72))
	for _, r := range rows {
		use := r.heurist
		if use == nil {
			use = r.sibling
		}
		if use == nil {
			continue
		}
		switch {
		case use.Tool != "":
			fmt.Printf("  {match: func(p string) bool { /* %s */ }, tool: %q, source: %q},\n",
				r.path, use.Tool, use.Source)
		case use.Note != "":
			fmt.Printf("  {match: func(p string) bool { /* %s */ }, note: %q},\n", r.path, use.Note)
		default:
			fmt.Printf("  {match: func(p string) bool { /* %s */ }, owner: %q},\n", r.path, use.Owner)
		}
	}
}

func printIf(format, v string) {
	if v != "" {
		fmt.Printf(format, v)
	}
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

// ---------------------------------------------------------------- output

// group preserves first-appearance order, which is what makes the report
// stable between runs (a Go map would reshuffle the sections).
type group struct {
	order []string
	items map[string][]string
}

func groupBy(cs []classification, key func(classification) string) *group {
	g := &group{items: map[string][]string{}}
	for _, c := range cs {
		k := key(c)
		if _, seen := g.items[k]; !seen {
			g.order = append(g.order, k)
		}
		g.items[k] = append(g.items[k], c.Path)
	}
	return g
}

func (g *group) print() {
	for _, k := range g.order {
		paths := g.items[k]
		fmt.Println()
		fmt.Printf("[%s]  (%d file%s)\n", k, len(paths), plural(len(paths)))
		for i, p := range paths {
			if i == 8 {
				fmt.Printf("  …and %d more\n", len(paths)-8)
				break
			}
			fmt.Printf("  %s\n", p)
		}
	}
}

func runAuditBoundary(args []string) int {
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, "pipeline:", err)
		return 1
	}
	all, err := auditWalk(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "pipeline:", err)
		return 1
	}
	classified := make([]classification, len(all))
	byPath := make(map[string]classification, len(all))
	for i, p := range all {
		classified[i] = classifyPath(p)
		byPath[p] = classified[i]
	}

	if has(args, "discover") {
		runDiscoverMode(root, all, byPath)
		return 0
	}

	var programmatic, toolSource, handAuthored, unknown []classification
	for _, c := range classified {
		switch c.Kind {
		case "programmatic":
			programmatic = append(programmatic, c)
		case "tool-source":
			toolSource = append(toolSource, c)
		case "hand-authored":
			handAuthored = append(handAuthored, c)
		default:
			unknown = append(unknown, c)
		}
	}
	drift := detectDrift(root, programmatic)

	if has(args, "--strict") {
		type driftRow struct {
			Path string `json:"path"`
			Tool string `json:"tool"`
		}
		rows := []driftRow{}
		for _, d := range drift {
			rows = append(rows, driftRow{d.Path, d.Tool})
		}
		out, _ := json.MarshalIndent(struct {
			Programmatic   int        `json:"programmatic"`
			ToolSource     int        `json:"tool_source"`
			HandAuthored   int        `json:"hand_authored"`
			Unknown        int        `json:"unknown"`
			LLMPatchPoints int        `json:"llm_patch_points"`
			Drift          []driftRow `json:"drift"`
		}{len(programmatic), len(toolSource), len(handAuthored), len(unknown),
			len(llmPatchPoints), rows}, "", "  ")
		fmt.Println(string(out))
		if len(drift) == 0 {
			return 0
		}
		return 1
	}

	fmt.Println("PROGRAMMATIC ZONE — regenerated by tools on `make build`")
	fmt.Println(strings.Repeat("=", 72))
	byTool := groupBy(programmatic, func(c classification) string {
		if c.Tool == "" {
			return "(unknown tool)"
		}
		return c.Tool
	})
	byTool.print()
	fmt.Print("\n\n\n\n")
	fmt.Println("HAND-AUTHORED ZONE — LLM/human edits expected, no script owns them")
	fmt.Println(strings.Repeat("=", 72))
	byOwner := groupBy(handAuthored, func(c classification) string {
		if c.Owner == "" {
			return "(unowned)"
		}
		return c.Owner
	})
	byOwner.print()
	fmt.Print("\n\n")
	fmt.Println("TOOL SOURCE — hand-written code that owns the PROGRAMMATIC ZONE")
	fmt.Println(strings.Repeat("=", 72))
	for _, p := range toolSourcePatterns {
		fmt.Println()
		fmt.Printf("[%s]\n", p.note)
		var matches []string
		for _, c := range toolSource {
			if p.test(c.Path) {
				matches = append(matches, c.Path)
			}
		}
		for i, m := range matches {
			if i == 8 {
				fmt.Printf("  …and %d more\n", len(matches)-8)
				break
			}
			fmt.Printf("  %s\n", m)
		}
	}
	fmt.Print("\n\n")
	fmt.Println("LLM PATCH POINTS — explicit hand-coded regions inside tool source")
	fmt.Println(strings.Repeat("=", 72))
	for _, p := range llmPatchPoints {
		fmt.Println()
		loc := p.File
		if p.Lines != "" {
			loc += ":" + p.Lines
		}
		fmt.Printf("[%s]\n", loc)
		fmt.Printf("  %s\n", p.What)
	}
	fmt.Print("\n\n")
	fmt.Println("DRIFT — tool-generated files with uncommitted changes")
	fmt.Println(strings.Repeat("=", 72))
	fmt.Println(`(Tool-generated file is "drift" if git status shows it as`)
	fmt.Println(" modified. NOTE: this is noisy right after `make build` — every")
	fmt.Println(" regenerated file appears as drift until committed. Run")
	fmt.Println(" `git status` to see if drift is from a fresh build vs a")
	fmt.Println(" manual edit. For CI gating, use --strict mode.)")
	switch {
	case len(drift) == 0:
		fmt.Println()
		fmt.Println("(none)")
	case len(drift) > 30:
		fmt.Println()
		fmt.Printf("(%d files — showing first 30; run `git status` for full list)\n", len(drift))
		for _, d := range drift[:30] {
			fmt.Printf("  %s  (%s)\n", d.Path, d.Tool)
		}
	default:
		fmt.Println()
		for _, d := range drift {
			fmt.Printf("  %s  (%s)\n", d.Path, d.Tool)
		}
	}
	fmt.Print("\n\n")
	fmt.Println("SUMMARY")
	fmt.Println(strings.Repeat("=", 72))
	fmt.Printf("  programmatic: %d files (regenerated by %d tools)\n", len(programmatic), len(byTool.order))
	fmt.Printf("  tool source: %d files (hand-written code that owns the PROGRAMMATIC zone)\n", len(toolSource))
	fmt.Printf("  hand-authored: %d files (in %d categories)\n", len(handAuthored), len(byOwner.order))
	fmt.Printf("  unknown: %d files (no pattern matched)\n", len(unknown))
	fmt.Printf("  LLM patch points: %d\n", len(llmPatchPoints))
	fmt.Printf("  drift: %d\n", len(drift))
	if len(unknown) > 0 {
		fmt.Println()
		fmt.Println("UNKNOWN files (no pattern matched — add to programmaticPatterns or handAuthoredPatterns):")
		for i, u := range unknown {
			if i == 20 {
				fmt.Printf("  …and %d more\n", len(unknown)-20)
				break
			}
			fmt.Printf("  %s\n", u.Path)
		}
	}
	return 0
}

// inManifest matches a path a tool recorded as its own output.
//
// The alternative is guessing from the path, and that guess is what made this
// audit report 331 generated files as owned by nobody: docs/demos looked
// hand-authored because most of it once was. A tool that writes a manifest is
// telling you what it owns; reading that is both correct today and correct
// after the tool's coverage changes.
//
// `field` is the key holding the path or the page name — example-oracle
// records {name, out} and example-fixture records {name}. A manifest that
// cannot be read matches nothing, so a missing file degrades to "unknown"
// rather than to a false claim of ownership.
func inManifest(manifest, field string) func(string) bool {
	var mu sync.Mutex
	var owned map[string]bool
	return func(p string) bool {
		mu.Lock()
		defer mu.Unlock()
		if owned == nil {
			// Only a SUCCESSFUL read is remembered. Caching the failure meant
			// one call made before the working directory was the repo root
			// poisoned every later call with an empty set, and every generated
			// page came back unowned.
			//
			// The root is found by walking up rather than taken from the cwd,
			// so this behaves the same whether it runs from the repo root (the
			// audit) or from pipeline/ (go test).
			cwd, err := os.Getwd()
			if err != nil {
				return false
			}
			root, err := findRepoRoot(cwd)
			if err != nil {
				return false
			}
			b, err := os.ReadFile(filepath.Join(root, manifest))
			if err != nil {
				return false
			}
			var rows []map[string]any
			if err := json.Unmarshal(b, &rows); err != nil {
				return false
			}
			m := map[string]bool{}
			for _, r := range rows {
				v, ok := r[field].(string)
				if !ok {
					continue
				}
				// "out" is already a repo path; "name" is a page stem
				if strings.Contains(v, "/") {
					m[v] = true
				} else {
					m["docs/demos/"+v+".html"] = true
				}
			}
			owned = m
		}
		return owned[p]
	}
}
