package main

import (
	"fmt"
	"strings"
)

// docs_overrides.go: hand-authored fixes for leaked upstream React JSX that
// rewriteLeakedJsxFences/rewriteInlineJsxMentions (docs_transforms.go) can't
// resolve mechanically — react hooks, framework-specific imports (next/link),
// or a JSX wrapper with no real DOM presence in the shipped markup (Popover/
// Tooltip/Dialog root components: the vanilla shape is trigger + <template>,
// no wrapping element — see docs_families.go's protocolMdx). Each entry is
// an exact-string find/replace against the page text, same contract as
// textAdjustments: a missing anchor is a loud build failure, not a silent
// skip, so an upstream re-pin can't silently drift stale content back in.
type jsxOverride struct {
	page string
	find string
	repl string
}

var jsxOverrides = []jsxOverride{
	{page: "attachment", find: "```tsx showLineNumbers\n<Dialog>\n  <Attachment>\n    {/* media, content, actions */}\n    <DialogTrigger asChild>\n      <AttachmentTrigger aria-label=\"Preview research-summary.pdf\" />\n    </DialogTrigger>\n  </Attachment>\n  <DialogContent>{/* ... */}</DialogContent>\n</Dialog>\n```\n", repl: "```html showLineNumbers\n<div data-slot=\"attachment\">\n  <!-- media, content, actions -->\n  <button data-slot=\"dialog-trigger\" id=\"<k>-trigger\" aria-label=\"Preview research-summary.pdf\"></button>\n</div>\n<template id=\"<k>-portal\">\n  <div data-slot=\"dialog-content\"><!-- ... --></div>\n</template>\n```"},
	{page: "attachment", find: "```tsx showLineNumbers\n<AttachmentTrigger asChild>\n  <a\n    href={url}\n    target=\"_blank\"\n    rel=\"noreferrer\"\n    aria-label=\"Open workspace.png\"\n  />\n</AttachmentTrigger>\n```\n", repl: "```html showLineNumbers\n<a data-slot=\"attachment-trigger\" href=\"/workspace.png\" target=\"_blank\" rel=\"noreferrer\" aria-label=\"Open workspace.png\"></a>\n```"},
	{page: "breadcrumb", find: "You can compose `<BreadcrumbItem />` with a `<DropdownMenu />` to create a dropdown in the breadcrumb.", repl: "You can compose a `data-slot=\"breadcrumb-item\"` with a dropdown-menu trigger (see the [Dropdown Menu](/docs/components/dropdown-menu) page) to create a dropdown in the breadcrumb."},
	{page: "bubble", find: "```tsx showLineNumbers\n<Bubble variant=\"muted\" align=\"end\">\n  <BubbleContent asChild>\n    <button type=\"button\" onClick={onReply}>\n      I forgot my password\n    </button>\n  </BubbleContent>\n</Bubble>\n```\n", repl: "```html showLineNumbers\n<div data-slot=\"bubble\">\n  <button type=\"button\" data-slot=\"bubble-content\">\n    I forgot my password\n  </button>\n</div>\n```\n\n`variant`/`align` compile into static Tailwind classes at build time (no runtime data attribute) — copy the class list for the variant you want from `dist/components/bubble.html`."},
	{page: "hover-card", find: "Use `openDelay` and `closeDelay` on the `HoverCard` to control when the card opens and\ncloses.\n\n```tsx showLineNumbers\n<HoverCard openDelay={100} closeDelay={200}>\n  <HoverCardTrigger>Hover</HoverCardTrigger>\n  <HoverCardContent>Content</HoverCardContent>\n</HoverCard>\n```\n", repl: "shadless's hover-card glue hardcodes `openDelay: 700, closeDelay: 300` (Radix's own defaults) in `dist/js/hover-card.js` — there is no markup prop to change them; edit that file directly if you need different timing."},
	{page: "hover-card", find: "## Positioning\n\nUse the `side` and `align` props on `HoverCardContent` to control placement.\n\n```tsx showLineNumbers\n<HoverCard>\n  <HoverCardTrigger>Hover</HoverCardTrigger>\n  <HoverCardContent side=\"top\" align=\"start\">\n    Content\n  </HoverCardContent>\n</HoverCard>\n```\n", repl: "## Positioning\n\nshadless's hover-card glue doesn't expose `side`/`align` through markup either — `popperOptions` in `dist/js/hover-card.js` only sets `sideOffset: 4`, so placement is whatever the kernel's popper default is (auto-flipping on collision); edit that file to pass a preferred placement."},
	{page: "carousel", find: "## Options\n\nYou can pass options to the carousel using the `opts` prop. See the [Embla Carousel docs](https://www.embla-carousel.com/api/options/) for more information.\n\n```tsx showLineNumbers {2-5}\n<Carousel\n  opts={{\n    align: \"start\",\n    loop: true,\n  }}\n>\n  <CarouselContent>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n  </CarouselContent>\n</Carousel>\n```\n", repl: "## Options\n\nshadless's carousel glue (`dist/js/carousel.js`) calls Embla with a fixed options object (`axis`/`direction`, derived from the markup) and nothing else — `align`/`loop`/every other [Embla option](https://www.embla-carousel.com/docs/api/options) is not exposed through markup. To change them, edit the `EmblaCarousel(viewport, { … })` call in that file directly; there is no declarative `opts` surface."},
	{page: "carousel", find: "## API\n\nUse a state and the `setApi` props to get an instance of the carousel API.\n\n<ComponentPreview\n  styleName=\"radix-nova\"\n  name=\"carousel-api\"\n  previewClassName=\"sm:h-[32rem]\"\n/>\n\n```tsx showLineNumbers {1,4,22}\nimport { type CarouselApi } from \"@/components/ui/carousel\"\n\nexport function Example() {\n  const [api, setApi] = React.useState<CarouselApi>()\n  const [current, setCurrent] = React.useState(0)\n  const [count, setCount] = React.useState(0)\n\n  React.useEffect(() => {\n    if (!api) {\n      return\n    }\n\n    setCount(api.scrollSnapList().length)\n    setCurrent(api.selectedScrollSnap() + 1)\n\n    api.on(\"select\", () => {\n      setCurrent(api.selectedScrollSnap() + 1)\n    })\n  }, [api])\n\n  return (\n    <Carousel setApi={setApi}>\n      <CarouselContent>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n      </CarouselContent>\n    </Carousel>\n  )\n}\n```\n\n## Events\n\nYou can listen to events using the api instance from `setApi`.\n\n```tsx showLineNumbers {1,4-14,16}\nimport { type CarouselApi } from \"@/components/ui/carousel\"\n\nexport function Example() {\n  const [api, setApi] = React.useState<CarouselApi>()\n\n  React.useEffect(() => {\n    if (!api) {\n      return\n    }\n\n    api.on(\"select\", () => {\n      // Do something on select.\n    })\n  }, [api])\n\n  return (\n    <Carousel setApi={setApi}>\n      <CarouselContent>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n      </CarouselContent>\n    </Carousel>\n  )\n}\n```\n", repl: "## API\n\nUse a state and the `setApi` props to get an instance of the carousel API.\n\n<ComponentPreview\n  styleName=\"radix-nova\"\n  name=\"carousel-api\"\n  previewClassName=\"sm:h-[32rem]\"\n/>\n\n```js showLineNumbers\nconst api = shadless.get(document.querySelector('[data-slot=\"carousel\"]'))\nlet current = api.selectedScrollSnap() + 1\nconst count = api.scrollSnapList().length\n\napi.on(\"select\", () => {\n  current = api.selectedScrollSnap() + 1\n})\n```\n\n## Events\n\nYou can listen to events on the instance `shadless.get(rootEl)` returns — it's the real Embla api, so its own `.on()` works exactly as [Embla's docs](https://www.embla-carousel.com/docs/api/events) describe.\n\n```js showLineNumbers\nconst api = shadless.get(document.querySelector('[data-slot=\"carousel\"]'))\n\napi.on(\"select\", () => {\n  // Do something on select.\n})\n```\n\n"},
	{page: "carousel", find: "## Plugins\n\nYou can use the `plugins` prop to add plugins to the carousel.\n\n```ts showLineNumbers {1,6-10}\nimport Autoplay from \"embla-carousel-autoplay\"\n\nexport function Example() {\n  return (\n    <Carousel\n      plugins={[\n        Autoplay({\n          delay: 2000,\n        }),\n      ]}\n    >\n      // ...\n    </Carousel>\n  )\n}\n```\n", repl: "## Plugins\n\nPlugins are an Embla concept (`EmblaCarousel(viewport, options, plugins)`) — shadless's glue (`dist/js/carousel.js`) doesn't pass a plugins array, so `embla-carousel-autoplay` and friends aren't available without editing that file yourself to add one."},
	{page: "navigation-menu", find: "## Link Component\n\nUse the `asChild` prop to compose a custom link component such as Next.js `Link`.\n\n```tsx showLineNumbers\nimport Link from \"next/link\"\n\nimport {\n  NavigationMenuItem,\n  NavigationMenuLink,\n  navigationMenuTriggerStyle,\n} from \"@/components/ui/navigation-menu\"\n\nexport function NavigationMenuDemo() {\n  return (\n    <NavigationMenuItem>\n      <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>\n        <Link href=\"/docs\">Documentation</Link>\n      </NavigationMenuLink>\n    </NavigationMenuItem>\n  )\n}\n```\n", repl: "## Link Component\n\nThere's no `asChild`/framework-Link composition in shadless — `navigation-menu-link` is a plain `<a>`, so just point `href` at whatever route your app uses:\n\n```html showLineNumbers\n<li data-slot=\"navigation-menu-item\">\n  <a data-slot=\"navigation-menu-link\" href=\"/docs\">Documentation</a>\n</li>\n```\n\n"},
	{page: "pagination", find: "## Next.js\n\nBy default the `<PaginationLink />` component will render an `<a />` tag.\n\nTo use the Next.js `<Link />` component, make the following updates to `pagination.tsx`.\n\n```diff showLineNumbers /typeof Link/ {1}\n+ import Link from \"next/link\"\n\n- type PaginationLinkProps = ... & React.ComponentProps<\"a\">\n+ type PaginationLinkProps = ... & React.ComponentProps<typeof Link>\n\nconst PaginationLink = ({...props }: ) => (\n  <PaginationItem>\n-   <a>\n+   <Link>\n      // ...\n-   </a>\n+   </Link>\n  </PaginationItem>\n)\n\n```\n\n<Callout className=\"mt-6\">\n\n**Note:** We are making updates to the cli to automatically do this for you.\n\n</Callout>\n\n", repl: "shadless has no CLI or framework Link component — `PaginationLink` always renders a real `<a>`; point `href` at whatever your router expects.\n\n"},
	{page: "spinner", find: "## Customization\n\nYou can replace the default spinner icon with any other icon by editing the `Spinner` component.\n\n<ComponentPreview styleName=\"radix-nova\" name=\"spinner-custom\" />\n\n```tsx showLineNumbers title=\"components/ui/spinner.tsx\"\nimport { LoaderIcon } from \"lucide-react\"\n\nimport { cn } from \"@/lib/utils\"\n\nfunction Spinner({ className, ...props }: React.ComponentProps<\"svg\">) {\n  return (\n    <LoaderIcon\n      role=\"status\"\n      aria-label=\"Loading\"\n      className={cn(\"size-4 animate-spin\", className)}\n      {...props}\n    />\n  )\n}\n\nexport { Spinner }\n```\n", repl: "## Customization\n\nYou can replace the default spinner icon with any other icon — swap the inner `<svg>` in `dist/components/spinner.html` for a different one.\n\n<ComponentPreview styleName=\"radix-nova\" name=\"spinner-custom\" />\n\n```html showLineNumbers title=\"dist/components/spinner.html\"\n<svg data-slot=\"spinner\">\n  <!-- swap this inner <svg> for a different icon's markup -->\n  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" aria-hidden=\"true\"><path d=\"...\"/></svg>\n</svg>\n```\n\nThe `size-4 animate-spin` styling ships as a `[data-slot=\"spinner\"]` CSS rule (`dist/css/spinner.css`), not an inline class — override it the same way, by targeting that selector.\n\n"},
	{page: "message-scroller", find: "```tsx\n<MessageScrollerContent aria-busy={status === \"streaming\"}>\n  {/* messages */}\n</MessageScrollerContent>\n```\n", repl: "```html\n<div data-slot=\"message-scroller-content\" aria-busy=\"true\">\n  <!-- messages -->\n</div>\n```\n\nToggle `aria-busy` yourself while a turn streams — there is no built-in status tracking."},
	{page: "carousel", find: "When localizing the carousel for RTL languages, you need to set the `direction` option in the `opts` prop to match the text direction. This ensures the carousel scrolls in the correct direction.\n\n```tsx showLineNumbers {2-5}\n<Carousel\n  dir={dir}\n  opts={{\n    direction: dir,\n  }}\n>\n  <CarouselContent>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n  </CarouselContent>\n  <CarouselPrevious className=\"rtl:rotate-180\" />\n  <CarouselNext className=\"rtl:rotate-180\" />\n</Carousel>\n```\n\nThe `direction` option accepts `\"ltr\"` or `\"rtl\"` and should match the `dir` prop value. You may also want to rotate the navigation buttons using the `rtl:rotate-180` class to ensure they point in the correct direction.\n", repl: "When localizing the carousel for RTL languages, set `dir=\"rtl\"` on the carousel root — the runtime reads that attribute directly (falling back to `<html dir>`). There's no `opts` to configure; `opts` isn't read at all (see [Options](#options)).\n\n```html showLineNumbers\n<div data-slot=\"carousel\" dir=\"rtl\">\n  <div data-slot=\"carousel-content\">\n    <div data-slot=\"carousel-item\">...</div>\n    <div data-slot=\"carousel-item\">...</div>\n    <div data-slot=\"carousel-item\">...</div>\n  </div>\n  <button data-slot=\"carousel-previous\" class=\"rtl:rotate-180\"></button>\n  <button data-slot=\"carousel-next\" class=\"rtl:rotate-180\"></button>\n</div>\n```\n"},
	{page: "table", find: "A table showing actions for each row using a `<DropdownMenu />` component.", repl: "A table showing actions for each row using a dropdown-menu trigger (see the [Dropdown Menu](/docs/components/dropdown-menu) page)."},
	{page: "rtl", find: "```tsx showLineNumbers /dir=\"rtl\"/\n<Popover>\n  <PopoverTrigger>Open</PopoverTrigger>\n  <PopoverContent dir=\"rtl\">\n    <div>Content</div>\n  </PopoverContent>\n</Popover>\n```\n", repl: "```html showLineNumbers /dir=\"rtl\"/\n<button data-slot=\"popover-trigger\" id=\"<k>-trigger\">Open</button>\n<template id=\"<k>-portal\">\n  <div data-slot=\"popover-content\" dir=\"rtl\">\n    <div>Content</div>\n  </div>\n</template>\n```"},
	{page: "rtl", find: "```tsx showLineNumbers /dir=\"rtl\"/\n<Tooltip>\n  <TooltipTrigger>Open</TooltipTrigger>\n  <TooltipContent dir=\"rtl\">\n    <div>Content</div>\n  </TooltipContent>\n</Tooltip>\n```\n", repl: "```html showLineNumbers /dir=\"rtl\"/\n<button data-slot=\"tooltip-trigger\" id=\"<k>-trigger\">Open</button>\n<template id=\"<k>-portal\">\n  <div data-slot=\"tooltip-content\" dir=\"rtl\">\n    <div>Content</div>\n  </div>\n</template>\n```"},
}

func applyJsxOverrides(page, raw string) (string, error) {
	out := raw
	for _, o := range jsxOverrides {
		if o.page != page {
			continue
		}
		if !strings.Contains(out, o.find) {
			return "", fmt.Errorf("%s: jsx override anchor not found — re-anchor against the new upstream content: %q", page, o.find)
		}
		out = strings.Replace(out, o.find, o.repl, 1)
	}
	return out, nil
}
