#!/usr/bin/env node
// Generate pipeline/nodes.go from gates/registry.mjs.
//
//   node pipeline/export-graph.mjs           rewrite nodes.go
//   node pipeline/export-graph.mjs --check   fail if it is out of date
//
// The definitions live in Go so the compiler checks them. That is the whole
// reason for generating source instead of JSON: JSON arrives through
// encoding/json, which silently ignores unknown fields and zero-fills missing
// ones, so the 41 node declarations — the part most worth checking — would be
// the one part no type ever saw. As Go source they are typed literals, and
// `needs` is []NodeID referencing generated constants, so a typo in a
// dependency is a compile error rather than a runtime lookup failure.
//
// Generated, not hand-written, because transcribing 41 nodes by hand is
// exactly how a gate goes quietly missing. gates/registry.mjs stays the source
// of truth while wireit still executes the graph; the --check mode is the
// same drift guard the wireit config already has.
import { NODES } from "../gates/registry.mjs"
import { readFileSync, writeFileSync } from "node:fs"
import { execFileSync } from "node:child_process"

const q = (s) => JSON.stringify(s)
const goID = (id) => "N" + id.replace(/(^|[-:])([a-z])/g, (_, __, c) => c.toUpperCase()).replace(/[-:]/g, "")

const consts = NODES.map((n) => `\t${goID(n.id)} NodeID = ${q(n.id)}`).join("\n")

// an empty slice literal must render as bare `nil`, not `[]T` + `nil`
const list = (type, xs, f = q) => xs.length ? `${type}{${xs.map(f).join(", ")}}` : "nil"
const runLit = (run) => run.length
  ? `[][]string{${run.map((c) => `{${c.map(q).join(", ")}}`).join(", ")}}` : "nil"

const body = NODES.map((n) => {
  const inputs = n.inputs === null ? "nil, // judges state outside the tree: never fresh"
    : `${list("[]string", n.inputs)},`
  return `\t{
\t\tID: ${goID(n.id)}, Kind: ${q(n.kind)}, Tier: ${q(n.tier)},
\t\tNeeds: ${list("[]NodeID", n.needs, goID)},
\t\tRun:      ${runLit(n.run ?? [])},
\t\tInputs:   ${inputs}
\t\tProduces: ${list("[]string", n.produces ?? [])},
\t}`
}).join(",\n")

const src = `// Code generated by pipeline/export-graph.mjs from gates/registry.mjs. DO NOT EDIT.
//
// Regenerate:  node pipeline/export-graph.mjs
// Check:       node pipeline/export-graph.mjs --check

package main

// NodeID is a defined type, not an alias: a bare string cannot stand in for
// one, so every reference below has to go through a generated constant and a
// typo in a dependency list is a compile error.
type NodeID string

const (
${consts}
)

// Nodes is the pipeline graph, in declaration order.
var Nodes = []Node{
${body},
}
`

const OUT = "pipeline/nodes.go"
// through gofmt, so --check compares against the same bytes a human editing
// the file would end up with
const formatted = execFileSync("gofmt", { input: src, encoding: "utf8" })
if (process.argv.includes("--check")) {
  let cur = ""
  try { cur = readFileSync(OUT, "utf8") } catch {}
  if (cur !== formatted) {
    console.error(`FAIL  pipeline-sync (${OUT} != gates/registry.mjs)\n` +
      `  regenerate:  node pipeline/export-graph.mjs`)
    process.exit(1)
  }
  console.log(`PASS  pipeline-sync (${OUT} == registry, ${NODES.length} nodes)`)
} else {
  writeFileSync(OUT, formatted)
  console.log(`${OUT}: ${NODES.length} nodes`)
}
