// Code generated by pipeline/export-graph.mjs from gates/registry.mjs. DO NOT EDIT.
//
// Regenerate:  node pipeline/export-graph.mjs
// Check:       node pipeline/export-graph.mjs --check

package main

// NodeID is a defined type, not an alias: a bare string cannot stand in for
// one, so every reference below has to go through a generated constant and a
// typo in a dependency list is a compile error.
type NodeID string

const (
	NPin                NodeID = "pin"
	NUnit               NodeID = "unit"
	NLedger             NodeID = "ledger"
	NPipelineSync       NodeID = "pipeline-sync"
	NDistComplete       NodeID = "dist-complete"
	NPack               NodeID = "pack"
	NCoverage           NodeID = "coverage"
	NOverlay            NodeID = "overlay"
	NConvert            NodeID = "convert"
	NEmit               NodeID = "emit"
	NEmitSmoke          NodeID = "emit-smoke"
	NBuildJs            NodeID = "build-js"
	NContractFixture    NodeID = "contract-fixture"
	NDemoBuild          NodeID = "demo-build"
	NExampleOracle      NodeID = "example-oracle"
	NExampleFixture     NodeID = "example-fixture"
	NDemoRtl            NodeID = "demo-rtl"
	NDemo               NodeID = "demo"
	NProductCss         NodeID = "product-css"
	NDemoCss            NodeID = "demo-css"
	NProductBuild       NodeID = "product-build"
	NProductVerify      NodeID = "product-verify"
	NConsumerSim        NodeID = "consumer-sim"
	NPathParity         NodeID = "path-parity"
	NDemoParity         NodeID = "demo-parity"
	NCssDirection       NodeID = "css-direction"
	NContracts          NodeID = "contracts"
	NOracleCss          NodeID = "oracle-css"
	NStyleParity        NodeID = "style-parity"
	NDemoSmoke          NodeID = "demo-smoke"
	NDocsCatalog        NodeID = "docs-catalog"
	NDocsBuild          NodeID = "docs-build"
	NDocsLinks          NodeID = "docs-links"
	NDocsConsistency    NodeID = "docs-consistency"
	NDocsFidelity       NodeID = "docs-fidelity"
	NDocsSmoke          NodeID = "docs-smoke"
	NDocsUpstream       NodeID = "docs-upstream"
	NInteractivitySweep NodeID = "interactivity-sweep"
	NReproducible       NodeID = "reproducible"
	NGoldenGate         NodeID = "golden-gate"
	NExampleGate        NodeID = "example-gate"
)

// Nodes is the pipeline graph, in declaration order.
var Nodes = []Node{
	{
		ID: NPin, Kind: "gate", Tier: "fast",
		Needs:    nil,
		Run:      [][]string{{"./build/pipeline", "pin", "--check-only"}},
		Inputs:   []string{"pipeline/gate_pin.go", "src/registry/pin.json", "vendor/**", ".upstream/shadcn-ui/.git/HEAD"},
		Produces: nil,
	},
	{
		ID: NUnit, Kind: "gate", Tier: "fast",
		Needs:    nil,
		Run:      [][]string{{"node", "tools/unit-check.mjs"}},
		Inputs:   []string{"tools/unit-check.mjs", "tools/unit/**", "src/**", "tools/**/*.mjs", "vendor/**", "package.json", "dist/esm/shadless.d.ts"},
		Produces: nil,
	},
	{
		ID: NLedger, Kind: "gate", Tier: "fast",
		Needs:    nil,
		Run:      [][]string{{"node", "gates/ledger.mjs", "--verify"}},
		Inputs:   []string{"gates/ledger.mjs", "gates/ledger.json", "gates/*-baseline.json", "src/registry/pin.json", "src/registry/upstream-snapshot/exemptions.json", "tools/contracts/components/**", "tools/interactivity-sweep.mjs", "src/**"},
		Produces: nil,
	},
	{
		ID: NPipelineSync, Kind: "gate", Tier: "fast",
		Needs:    nil,
		Run:      [][]string{{"node", "pipeline/export-graph.mjs", "--check"}},
		Inputs:   []string{"pipeline/export-graph.mjs", "pipeline/nodes.go", "gates/registry.mjs"},
		Produces: nil,
	},
	{
		ID: NDistComplete, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NDemoCss, NProductCss},
		Run:      [][]string{{"./build/pipeline", "gate", "dist-complete"}},
		Inputs:   []string{"pipeline/gate_dist_complete.go", "dist/css/**", "dist/out.css"},
		Produces: nil,
	},
	{
		ID: NPack, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NBuildJs, NProductBuild},
		Run:      [][]string{{"./build/pipeline", "gate", "pack"}},
		Inputs:   []string{"pipeline/gate_pack.go", "package.json", "README.md", "dist/**"},
		Produces: nil,
	},
	{
		ID: NCoverage, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NConvert, NExampleOracle},
		Run:      [][]string{{"node", "gates/coverage.mjs", "--check"}},
		Inputs:   []string{"gates/coverage.mjs", "gates/ledger.json", "src/registry/tiers.json", "src/registry/ir/**", "docs/example-oracle.json", "docs/demos/**", "tools/contracts/components/**", "tools/interactivity-sweep.mjs"},
		Produces: nil,
	},
	{
		ID: NOverlay, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NConvert, NExampleOracle},
		Run:      [][]string{{"node", "gates/overlay.mjs", "--audit"}},
		Inputs:   []string{"gates/overlay.mjs", "overlays/**", "src/**", "tools/**/*.mjs", "docs/example-oracle.json", "docs/example-fixture-targets.json", "docs/demos/**", "src/registry/pin.json"},
		Produces: nil,
	},
	{
		ID: NConvert, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NPin},
		Run:      [][]string{{"node", "tools/resolve-skins.mjs"}, {"node", "src/converter/index.mjs"}},
		Inputs:   []string{"tools/resolve-skins.mjs", "src/converter/**", "src/tags.mjs", "src/emitter/skin.mjs", "src/registry/tiers.json", "src/registry/pin.json", "src/kernel/**"},
		Produces: []string{"src/registry/ir", "build/resolved-ui"},
	},
	{
		ID: NEmit, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NConvert},
		Run:      [][]string{{"node", "src/emitter/index.mjs"}, {"node", "tools/tw.mjs", "build/emit/globals.css", "build/emit/out.css", "--cwd", "dist"}},
		Inputs:   []string{"src/emitter/**", "src/tags.mjs", "src/docs/theme-prepaint.mjs", "src/registry/tiers.json", "src/registry/pin.json", "probes/h4/globals.css", "tools/tw.mjs"},
		Produces: []string{"dist/components/*.html", "!dist/components/*-rtl-*.html", "dist/shadless.css", "build/emit"},
	},
	{
		ID: NEmitSmoke, Kind: "gate", Tier: "medium",
		Needs:    []NodeID{NEmit},
		Run:      [][]string{{"node", "src/emitter/smoke.mjs"}},
		Inputs:   []string{"src/emitter/smoke.mjs", "src/registry/tiers.json", "src/registry/ir/**", "dist/components/**"},
		Produces: nil,
	},
	{
		ID: NBuildJs, Kind: "build", Tier: "fast",
		Needs:    nil,
		Run:      [][]string{{"node", "tools/build-js.mjs"}},
		Inputs:   []string{"tools/build-js.mjs", "src/runtime/**", "vendor/**"},
		Produces: []string{"dist/shadless.js", "dist/js", "dist/shadless.min.js", "dist/esm"},
	},
	{
		ID: NContractFixture, Kind: "build", Tier: "full",
		Needs:    []NodeID{NConvert, NBuildJs},
		Run:      [][]string{{"node", "tools/example-fixture.mjs", "--contracts"}},
		Inputs:   []string{"tools/example-fixture.mjs", "tools/contracts/oracle-build.mjs", "tools/contracts/components/**", "tools/fixture-families.mjs", "src/docs/theme-prepaint.mjs", "docs/example-fixture-targets.json", "tools/oracle-lib.mjs", "tools/contracts/stubs/**", "tools/resolve-skins.mjs", "src/registry/pin.json", "package-lock.json"},
		Produces: []string{"src/kernel/*.html"},
	},
	{
		ID: NDemoBuild, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NEmit},
		Run:      [][]string{{"node", "tools/build-demo.mjs"}},
		Inputs:   []string{"tools/build-demo.mjs", "src/docs/theme-prepaint.mjs"},
		Produces: []string{"dist/components/*-demo.html", "!dist/components/*-rtl-*.html"},
	},
	{
		ID: NExampleOracle, Kind: "build", Tier: "full",
		Needs:    []NodeID{NDemoBuild},
		Run:      [][]string{{"node", "tools/example-oracle.mjs"}},
		Inputs:   []string{"tools/example-oracle.mjs", "src/docs/theme-prepaint.mjs", "src/registry/tiers.json", "src/runtime/components/**", "docs/catalog.json", "tools/oracle-lib.mjs", "tools/contracts/stubs/**", "tools/resolve-skins.mjs", "src/registry/pin.json", "src/registry/upstream-snapshot/exemptions.json", "package-lock.json"},
		Produces: []string{"docs/demos/*.html", "!docs/demos/*-rtl-*.html", "docs/example-oracle.json", "docs/example-fixture-targets.json"},
	},
	{
		ID: NExampleFixture, Kind: "build", Tier: "full",
		Needs:    []NodeID{NExampleOracle},
		Run:      [][]string{{"node", "tools/example-fixture.mjs"}},
		Inputs:   []string{"tools/example-fixture.mjs", "tools/contracts/oracle-build.mjs", "tools/contracts/components/**", "tools/fixture-families.mjs", "src/docs/theme-prepaint.mjs", "docs/example-fixture-targets.json", "dist/js/**", "tools/oracle-lib.mjs", "tools/contracts/stubs/**", "tools/resolve-skins.mjs", "src/registry/pin.json", "package-lock.json"},
		Produces: []string{"docs/demos/*.html", "!docs/demos/*-rtl-*.html"},
	},
	{
		ID: NDemoRtl, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NExampleOracle},
		Run:      [][]string{{"node", "tools/build-rtl.mjs"}},
		Inputs:   []string{"tools/build-rtl.mjs", "tools/rtl-lib.mjs", "src/docs/theme-prepaint.mjs", "src/registry/pin.json"},
		Produces: []string{"dist/components/*-rtl-*.html", "docs/demos/*-rtl-*.html", "build/rtl-langs.json"},
	},
	{
		ID: NDemo, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NDemoRtl, NExampleFixture, NContractFixture, NBuildJs},
		Run:      [][]string{{"node", "tools/demo.mjs"}},
		Inputs:   []string{"tools/demo.mjs", "tools/demo-lib.mjs", "tools/build-js.mjs", "src/emitter/css.mjs", "src/docs/theme-prepaint.mjs", "src/registry/tiers.json", "src/registry/ir/**", "src/kernel/**", "probes/h4/globals.css", "probes/t7/**", "probes/t8/**"},
		Produces: []string{"dist/globals.css", "dist/demo-index.html", "dist/css", "dist/components/*.html", "!dist/components/*-rtl-*.html"},
	},
	{
		ID: NProductCss, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NDemo},
		Run:      [][]string{{"node", "tools/product-css.mjs"}},
		Inputs:   []string{"tools/product-css.mjs", "src/docs/theme-prepaint.mjs", "probes/h4/globals.css", "package-lock.json"},
		Produces: []string{"dist/shadless-core.css", "dist/shadless.product.css"},
	},
	{
		ID: NDemoCss, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NDemo},
		Run:      [][]string{{"node", "tools/tw.mjs", "dist/globals.css", "dist/out.css", "--cwd", "."}},
		Inputs:   []string{"tools/tw.mjs", "dist/globals.css", "dist/components/**", "dist/js/**", "docs/demos/**", "docs/content/**", "src/kernel/**", "tools/contracts/out/**", "src/registry/ir/**", "probes/t7/**", "probes/t8/**"},
		Produces: []string{"dist/out.css"},
	},
	{
		ID: NProductBuild, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NProductCss},
		Run:      [][]string{{"node", "tools/tw.mjs", "dist/shadless.product.css", "dist/shadless.full.css"}, {"node", "tools/tw.mjs", "dist/shadless.product.css", "dist/shadless.full.min.css", "--minify"}},
		Inputs:   []string{"tools/tw.mjs", "dist/shadless.product.css"},
		Produces: []string{"dist/shadless.full.css", "dist/shadless.full.min.css"},
	},
	{
		ID: NProductVerify, Kind: "gate", Tier: "medium",
		Needs:    []NodeID{NProductBuild, NDemoCss},
		Run:      [][]string{{"node", "tools/product-css.mjs", "--verify"}},
		Inputs:   []string{"tools/product-css.mjs", "dist/**"},
		Produces: nil,
	},
	{
		ID: NConsumerSim, Kind: "gate", Tier: "medium",
		Needs:    []NodeID{NProductCss},
		Run:      [][]string{{"node", "tools/consumer-sim.mjs"}},
		Inputs:   []string{"tools/consumer-sim.mjs", "dist/css/**", "dist/shadless-core.css", "package.json"},
		Produces: nil,
	},
	{
		ID: NPathParity, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NProductBuild, NOracleCss},
		Run:      [][]string{{"node", "gates/path-parity.mjs"}},
		Inputs:   []string{"gates/path-parity.mjs", "gates/parity-baseline.mjs", "gates/path-parity-baseline.json", "gates/ledger.json", "src/emitter/css.mjs", "src/tags.mjs", "src/registry/ir/**", "dist/css/**", "dist/shadless.full.css", "build/gates/oracle.css", "src/registry/pin.json", "tools/tw.mjs"},
		Produces: nil,
	},
	{
		ID: NDemoParity, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDemoCss, NOracleCss, NExampleOracle},
		Run:      [][]string{{"node", "gates/demo-parity.mjs"}},
		Inputs:   []string{"gates/demo-parity.mjs", "gates/parity-baseline.mjs", "gates/demo-parity-baseline.json", "gates/ledger.json", "build/gates/oracle.css", "dist/out.css", "docs/demos/**", "docs/example-oracle.json"},
		Produces: nil,
	},
	{
		ID: NCssDirection, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NDemoCss},
		Run:      [][]string{{"node", "tools/css-direction-gate.mjs"}},
		Inputs:   []string{"tools/css-direction-gate.mjs", "dist/shadless.css"},
		Produces: nil,
	},
	{
		ID: NContracts, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDemoCss},
		Run:      [][]string{{"npm", "run", "contracts"}},
		Inputs:   []string{"tools/contracts/**/*.mjs", "tools/contracts/stubs/**", "tools/contracts/components/**", "tools/oracle-lib.mjs", "dist/**", "src/kernel/**", "src/registry/pin.json", "package-lock.json", "gates/ledger.json"},
		Produces: []string{"tools/contracts/out"},
	},
	{
		ID: NOracleCss, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NConvert},
		Run:      [][]string{{"node", "gates/oracle-css.mjs"}},
		Inputs:   []string{"gates/oracle-css.mjs", "tools/tw.mjs", "src/registry/pin.json", "build/resolved-ui/**"},
		Produces: []string{"build/gates/oracle.css"},
	},
	{
		ID: NStyleParity, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NContracts, NOracleCss},
		Run:      [][]string{{"node", "tools/style-parity.mjs"}},
		Inputs:   []string{"tools/style-parity.mjs", "gates/parity-baseline.mjs", "gates/style-parity-baseline.json", "gates/ledger.json", "tools/contracts/out/**", "tools/contracts/components/**", "build/gates/oracle.css", "src/registry/pin.json"},
		Produces: nil,
	},
	{
		ID: NDemoSmoke, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDemoCss},
		Run:      [][]string{{"node", "tools/demo-smoke.mjs"}},
		Inputs:   []string{"tools/demo-smoke.mjs", "dist/**", "src/registry/ir/**", "src/registry/tiers.json"},
		Produces: nil,
	},
	{
		ID: NDocsCatalog, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NDemo},
		Run:      [][]string{{"node", "tools/docs-catalog.mjs"}},
		Inputs:   []string{"tools/docs-catalog.mjs", "src/registry/pin.json", "src/registry/tiers.json", "dist/components/**", "docs/demos/**"},
		Produces: []string{"docs/catalog.json"},
	},
	{
		ID: NDocsBuild, Kind: "build", Tier: "medium",
		Needs:    []NodeID{NDocsCatalog, NDemoCss},
		Run:      [][]string{{"node", "tools/docs-build.mjs"}},
		Inputs:   []string{"tools/docs-build.mjs", "tools/docs-guides.mjs", "tools/docs-page-lib.mjs", "tools/fixture-families.mjs", "src/docs/**", "docs/catalog.json", "docs/content/**", "docs/fonts/**", "dist/**", "docs/demos/**", "build/rtl-langs.json", "src/registry/ir/**", "src/registry/pin.json", "package.json", "package-lock.json"},
		Produces: []string{"docs/site", "docs/content-map.json"},
	},
	{
		ID: NDocsLinks, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/docs-links.mjs"}},
		Inputs:   []string{"tools/docs-links.mjs", "tools/docs-guides.mjs", "docs/site/**"},
		Produces: nil,
	},
	{
		ID: NDocsConsistency, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/docs-consistency.mjs"}},
		Inputs:   []string{"tools/docs-consistency.mjs", "src/docs/theme-prepaint.mjs", "docs/site/**", "dist/**", "docs/demos/**", "docs/catalog.json", "package.json"},
		Produces: nil,
	},
	{
		ID: NDocsFidelity, Kind: "gate", Tier: "fast",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/docs-fidelity.mjs"}},
		Inputs:   []string{"tools/docs-fidelity.mjs", "tools/docs-fidelity-lib.mjs", "tools/docs-guides.mjs", "src/docs/transforms.mjs", "docs/site/**", "docs/content-map.json", "docs/content/**", "src/registry/pin.json"},
		Produces: nil,
	},
	{
		ID: NDocsSmoke, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/docs-smoke.mjs", "--all"}},
		Inputs:   []string{"tools/docs-smoke.mjs", "tools/docs-guides.mjs", "docs/site/**"},
		Produces: nil,
	},
	{
		ID: NDocsUpstream, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/docs-upstream.mjs"}},
		Inputs:   []string{"tools/docs-upstream.mjs", "docs/site/**"},
		Produces: nil,
	},
	{
		ID: NInteractivitySweep, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/interactivity-sweep.mjs"}},
		Inputs:   []string{"tools/interactivity-sweep.mjs", "docs/site/**", "src/registry/tiers.json", "gates/ledger.json"},
		Produces: nil,
	},
	{
		ID: NReproducible, Kind: "gate", Tier: "medium",
		Needs:    []NodeID{NDocsBuild, NProductBuild, NDemoRtl, NExampleFixture},
		Run:      [][]string{{"./build/pipeline", "gate", "reproducible"}},
		Inputs:   nil, // judges state outside the tree: never fresh
		Produces: nil,
	},
	{
		ID: NGoldenGate, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NExampleOracle},
		Run:      [][]string{{"node", "tools/example-golden.mjs"}},
		Inputs:   []string{"tools/example-golden.mjs", "src/registry/upstream-snapshot/**", "gates/ledger.json", "tools/oracle-lib.mjs", "tools/contracts/stubs/**", "tools/resolve-skins.mjs", "src/registry/pin.json", "package-lock.json"},
		Produces: nil,
	},
	{
		ID: NExampleGate, Kind: "gate", Tier: "full",
		Needs:    []NodeID{NDocsBuild},
		Run:      [][]string{{"node", "tools/example-oracle.mjs", "--check"}},
		Inputs:   []string{"tools/example-oracle.mjs", "docs/demos/**", "docs/example-oracle.json", "src/registry/tiers.json", "tools/oracle-lib.mjs", "tools/contracts/stubs/**", "tools/resolve-skins.mjs", "src/registry/pin.json", "package-lock.json"},
		Produces: nil,
	},
}
