package main

import (
	"fmt"
	"strings"
)

// docs_overrides.go: hand-authored fixes for leaked upstream React JSX that
// rewriteLeakedJsxFences/rewriteInlineJsxMentions (docs_transforms.go) can't
// resolve mechanically — react hooks, framework-specific imports (next/link),
// or a JSX wrapper with no real DOM presence in the shipped markup (Popover/
// Tooltip/Dialog root components: the vanilla shape is trigger + <template>,
// no wrapping element — see docs_families.go's protocolMdx). Each entry is
// an exact-string find/replace against the page text, same contract as
// textAdjustments: a missing anchor is a loud build failure, not a silent
// skip, so an upstream re-pin can't silently drift stale content back in.
type jsxOverride struct {
	page string
	find string
	repl string
}

var jsxOverrides = []jsxOverride{
	{page: "attachment", find: "```tsx showLineNumbers\n<Dialog>\n  <Attachment>\n    {/* media, content, actions */}\n    <DialogTrigger asChild>\n      <AttachmentTrigger aria-label=\"Preview research-summary.pdf\" />\n    </DialogTrigger>\n  </Attachment>\n  <DialogContent>{/* ... */}</DialogContent>\n</Dialog>\n```\n", repl: "```html showLineNumbers\n<div data-slot=\"attachment\">\n  <!-- media, content, actions -->\n  <button data-slot=\"dialog-trigger\" id=\"<k>-trigger\" aria-label=\"Preview research-summary.pdf\"></button>\n</div>\n<template id=\"<k>-portal\">\n  <div data-slot=\"dialog-content\"><!-- ... --></div>\n</template>\n```"},
	{page: "attachment", find: "```tsx showLineNumbers\n<AttachmentTrigger asChild>\n  <a\n    href={url}\n    target=\"_blank\"\n    rel=\"noreferrer\"\n    aria-label=\"Open workspace.png\"\n  />\n</AttachmentTrigger>\n```\n", repl: "```html showLineNumbers\n<a data-slot=\"attachment-trigger\" href=\"/workspace.png\" target=\"_blank\" rel=\"noreferrer\" aria-label=\"Open workspace.png\"></a>\n```"},
	{page: "breadcrumb", find: "You can compose `<BreadcrumbItem />` with a `<DropdownMenu />` to create a dropdown in the breadcrumb.", repl: "You can compose a `data-slot=\"breadcrumb-item\"` with a dropdown-menu trigger (see the [Dropdown Menu](/docs/components/dropdown-menu) page) to create a dropdown in the breadcrumb."},
	{page: "bubble", find: "```tsx showLineNumbers\n<Bubble variant=\"muted\" align=\"end\">\n  <BubbleContent asChild>\n    <button type=\"button\" onClick={onReply}>\n      I forgot my password\n    </button>\n  </BubbleContent>\n</Bubble>\n```\n", repl: "```html showLineNumbers\n<div data-slot=\"bubble\" data-variant=\"muted\" data-align=\"end\">\n  <button type=\"button\" data-slot=\"bubble-content\">\n    I forgot my password\n  </button>\n</div>\n```\n\nThere is no `asChild`: put `data-slot=\"bubble-content\"` on the real `<button>` (or `<a>`) itself, and wire your click handler to it like any other element."},
	{page: "hover-card", find: "Use `openDelay` and `closeDelay` on the `HoverCard` to control when the card opens and\ncloses.\n\n```tsx showLineNumbers\n<HoverCard openDelay={100} closeDelay={200}>\n  <HoverCardTrigger>Hover</HoverCardTrigger>\n  <HoverCardContent>Content</HoverCardContent>\n</HoverCard>\n```\n", repl: "shadless's hover-card glue hardcodes `openDelay: 700, closeDelay: 300` (Radix's own defaults) in `dist/js/hover-card.js` — there is no markup prop to change them; edit that file directly if you need different timing."},
	{page: "hover-card", find: "## Positioning\n\nUse the `side` and `align` props on `HoverCardContent` to control placement.\n\n```tsx showLineNumbers\n<HoverCard>\n  <HoverCardTrigger>Hover</HoverCardTrigger>\n  <HoverCardContent side=\"top\" align=\"start\">\n    Content\n  </HoverCardContent>\n</HoverCard>\n```\n", repl: "## Positioning\n\nshadless's hover-card glue doesn't expose `side`/`align` through markup either — `popperOptions` in `dist/js/hover-card.js` only sets `sideOffset: 4`, so placement is whatever the kernel's popper default is (auto-flipping on collision); edit that file to pass a preferred placement."},
	{page: "carousel", find: "## Options\n\nYou can pass options to the carousel using the `opts` prop. See the [Embla Carousel docs](https://www.embla-carousel.com/api/options/) for more information.\n\n```tsx showLineNumbers {2-5}\n<Carousel\n  opts={{\n    align: \"start\",\n    loop: true,\n  }}\n>\n  <CarouselContent>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n  </CarouselContent>\n</Carousel>\n```\n", repl: "## Options\n\nshadless's carousel glue (`dist/js/carousel.js`) calls Embla with a fixed options object (`axis`/`direction`, derived from the markup) and nothing else — `align`/`loop`/every other [Embla option](https://www.embla-carousel.com/docs/api/options) is not exposed through markup. To change them, edit the `EmblaCarousel(viewport, { … })` call in that file directly; there is no declarative `opts` surface."},
	{page: "carousel", find: "## API\n\nUse a state and the `setApi` props to get an instance of the carousel API.\n\n<ComponentPreview\n  styleName=\"radix-nova\"\n  name=\"carousel-api\"\n  previewClassName=\"sm:h-[32rem]\"\n/>\n\n```tsx showLineNumbers {1,4,22}\nimport { type CarouselApi } from \"@/components/ui/carousel\"\n\nexport function Example() {\n  const [api, setApi] = React.useState<CarouselApi>()\n  const [current, setCurrent] = React.useState(0)\n  const [count, setCount] = React.useState(0)\n\n  React.useEffect(() => {\n    if (!api) {\n      return\n    }\n\n    setCount(api.scrollSnapList().length)\n    setCurrent(api.selectedScrollSnap() + 1)\n\n    api.on(\"select\", () => {\n      setCurrent(api.selectedScrollSnap() + 1)\n    })\n  }, [api])\n\n  return (\n    <Carousel setApi={setApi}>\n      <CarouselContent>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n      </CarouselContent>\n    </Carousel>\n  )\n}\n```\n\n## Events\n\nYou can listen to events using the api instance from `setApi`.\n\n```tsx showLineNumbers {1,4-14,16}\nimport { type CarouselApi } from \"@/components/ui/carousel\"\n\nexport function Example() {\n  const [api, setApi] = React.useState<CarouselApi>()\n\n  React.useEffect(() => {\n    if (!api) {\n      return\n    }\n\n    api.on(\"select\", () => {\n      // Do something on select.\n    })\n  }, [api])\n\n  return (\n    <Carousel setApi={setApi}>\n      <CarouselContent>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n        <CarouselItem>...</CarouselItem>\n      </CarouselContent>\n    </Carousel>\n  )\n}\n```\n", repl: "## API\n\nUse a state and the `setApi` props to get an instance of the carousel API.\n\n<ComponentPreview\n  styleName=\"radix-nova\"\n  name=\"carousel-api\"\n  previewClassName=\"sm:h-[32rem]\"\n/>\n\n```js showLineNumbers\nconst api = shadless.get(document.querySelector('[data-slot=\"carousel\"]'))\nlet current = api.selectedScrollSnap() + 1\nconst count = api.scrollSnapList().length\n\napi.on(\"select\", () => {\n  current = api.selectedScrollSnap() + 1\n})\n```\n\n## Events\n\nYou can listen to events on the instance `shadless.get(rootEl)` returns — it's the real Embla api, so its own `.on()` works exactly as [Embla's docs](https://www.embla-carousel.com/docs/api/events) describe.\n\n```js showLineNumbers\nconst api = shadless.get(document.querySelector('[data-slot=\"carousel\"]'))\n\napi.on(\"select\", () => {\n  // Do something on select.\n})\n```\n\n"},
	{page: "carousel", find: "## Plugins\n\nYou can use the `plugins` prop to add plugins to the carousel.\n\n```ts showLineNumbers {1,6-10}\nimport Autoplay from \"embla-carousel-autoplay\"\n\nexport function Example() {\n  return (\n    <Carousel\n      plugins={[\n        Autoplay({\n          delay: 2000,\n        }),\n      ]}\n    >\n      // ...\n    </Carousel>\n  )\n}\n```\n", repl: "## Plugins\n\nPlugins are an Embla concept (`EmblaCarousel(viewport, options, plugins)`) — shadless's glue (`dist/js/carousel.js`) doesn't pass a plugins array, so `embla-carousel-autoplay` and friends aren't available without editing that file yourself to add one."},
	{page: "navigation-menu", find: "## Link Component\n\nUse the `asChild` prop to compose a custom link component such as Next.js `Link`.\n\n```tsx showLineNumbers\nimport Link from \"next/link\"\n\nimport {\n  NavigationMenuItem,\n  NavigationMenuLink,\n  navigationMenuTriggerStyle,\n} from \"@/components/ui/navigation-menu\"\n\nexport function NavigationMenuDemo() {\n  return (\n    <NavigationMenuItem>\n      <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>\n        <Link href=\"/docs\">Documentation</Link>\n      </NavigationMenuLink>\n    </NavigationMenuItem>\n  )\n}\n```\n", repl: "## Link Component\n\nThere's no `asChild`/framework-Link composition in shadless — `navigation-menu-link` is a plain `<a>`, so just point `href` at whatever route your app uses:\n\n```html showLineNumbers\n<li data-slot=\"navigation-menu-item\">\n  <a data-slot=\"navigation-menu-link\" href=\"/docs\">Documentation</a>\n</li>\n```\n\n"},
	{page: "pagination", find: "## Next.js\n\nBy default the `<PaginationLink />` component will render an `<a />` tag.\n\nTo use the Next.js `<Link />` component, make the following updates to `pagination.tsx`.\n\n```diff showLineNumbers /typeof Link/ {1}\n+ import Link from \"next/link\"\n\n- type PaginationLinkProps = ... & React.ComponentProps<\"a\">\n+ type PaginationLinkProps = ... & React.ComponentProps<typeof Link>\n\nconst PaginationLink = ({...props }: ) => (\n  <PaginationItem>\n-   <a>\n+   <Link>\n      // ...\n-   </a>\n+   </Link>\n  </PaginationItem>\n)\n\n```\n\n<Callout className=\"mt-6\">\n\n**Note:** We are making updates to the cli to automatically do this for you.\n\n</Callout>\n\n", repl: "shadless has no CLI or framework Link component — `PaginationLink` always renders a real `<a>`; point `href` at whatever your router expects.\n\n"},
	{page: "spinner", find: "## Customization\n\nYou can replace the default spinner icon with any other icon by editing the `Spinner` component.\n\n<ComponentPreview styleName=\"radix-nova\" name=\"spinner-custom\" />\n\n```tsx showLineNumbers title=\"components/ui/spinner.tsx\"\nimport { LoaderIcon } from \"lucide-react\"\n\nimport { cn } from \"@/lib/utils\"\n\nfunction Spinner({ className, ...props }: React.ComponentProps<\"svg\">) {\n  return (\n    <LoaderIcon\n      role=\"status\"\n      aria-label=\"Loading\"\n      className={cn(\"size-4 animate-spin\", className)}\n      {...props}\n    />\n  )\n}\n\nexport { Spinner }\n```\n", repl: "## Customization\n\nYou can replace the default spinner icon with any other icon — swap the inner `<svg>` in the spinner markup for a different one.\n\n<ComponentPreview styleName=\"radix-nova\" name=\"spinner-custom\" />\n\n```html showLineNumbers\n<svg data-slot=\"spinner\">\n  <!-- swap this inner <svg> for a different icon's markup -->\n  <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" aria-hidden=\"true\"><path d=\"...\"/></svg>\n</svg>\n```\n\nThe `size-4 animate-spin` styling ships as a `[data-slot=\"spinner\"]` CSS rule (`dist/css/spinner.css`), not an inline class — override it the same way, by targeting that selector.\n\n"},
	{page: "rtl", find: "For now, make sure you pass in the `dir` prop to portal elements.", repl: "For now, set the `dir` attribute on the portal content element itself."},
	{page: "rtl", find: "When you install components, the CLI automatically transforms physical positioning classes to logical equivalents, so your components work seamlessly in both LTR and RTL contexts.", repl: "shadless has no install step that rewrites anything: the classes you see are the pinned registry's own. What makes the difference is which example you start from — the pages below ship an RTL variant beside the LTR one wherever upstream authored it."},
	{page: "rtl", find: "The CLI also handles animation classes, automatically transforming physical directional animations to their logical equivalents. For example, `slide-in-from-right` becomes `slide-in-from-end`.\n\nThis ensures animations like dropdowns, popovers, and tooltips animate in the correct direction based on the document's text direction.", repl: "Animation utilities are emitted as the registry writes them, physical names included — nothing rewrites `slide-in-from-right` into `slide-in-from-end` for you. Where upstream's own RTL example uses the logical name, the shipped `-rtl` page carries it; elsewhere, set the direction on the element yourself."},
	{page: "message-scroller", find: "```tsx\n<MessageScrollerContent aria-busy={status === \"streaming\"}>\n  {/* messages */}\n</MessageScrollerContent>\n```\n\nPass `aria-busy` while a turn streams if announcements should wait for the\ncompleted message row.\n", repl: "```html\n<div data-slot=\"message-scroller-content\" aria-busy=\"true\">\n  <!-- messages -->\n</div>\n```\n\nToggle `aria-busy` yourself while a turn streams, so announcements wait for the completed message row — there is no built-in status tracking.\n"},
	{page: "message-scroller", find: "It uses `role=\"region\"`, `aria-label=\"Messages\"`, and `tabIndex={0}`,", repl: "It uses `role=\"region\"`, `aria-label=\"Messages\"`, and `tabindex=\"0\"`,"},
	{page: "message-scroller", find: "`MessageScrollerButton` renders a real button. When there is nothing to scroll\ntoward, it sets `inert`, uses `tabIndex={-1}`, and exposes `data-active=\"false\"`\nso inactive scroll controls do not create extra focus stops.", repl: "The scroll button is a real `<button data-slot=\"message-scroller-button\">`, and when there is nothing to scroll toward it exposes `data-active=\"false\"`. Nothing else follows from that here: no shipped stylesheet reads `data-active` on this slot (only `dist/css/tabs.css` and `dist/css/navigation-menu.css` use that attribute at all), and the button sets neither `inert` nor `tabindex=\"-1\"`. Style the attribute and take the inactive control out of the focus order yourself."},
	{page: "message-scroller", find: "## Unstyled\n\nThe behavior in `MessageScroller` comes from the `@shadcn/react` package. To use\nit directly with your own markup and styles, see\n[Message Scroller](/docs/react/message-scroller) under @shadcn/react.\n", repl: "## Unstyled\n\nThere is no behavior package to reach past: the shipped markup IS the whole component. Copy any example on this page and restyle it — the `data-slot` names are the only contract.\n"},
	{page: "carousel", find: "When localizing the carousel for RTL languages, you need to set the `direction` option in the `opts` prop to match the text direction. This ensures the carousel scrolls in the correct direction.\n\n```tsx showLineNumbers {2-5}\n<Carousel\n  dir={dir}\n  opts={{\n    direction: dir,\n  }}\n>\n  <CarouselContent>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n  </CarouselContent>\n  <CarouselPrevious className=\"rtl:rotate-180\" />\n  <CarouselNext className=\"rtl:rotate-180\" />\n</Carousel>\n```\n\nThe `direction` option accepts `\"ltr\"` or `\"rtl\"` and should match the `dir` prop value. You may also want to rotate the navigation buttons using the `rtl:rotate-180` class to ensure they point in the correct direction.\n", repl: "When localizing the carousel for RTL languages, set `dir=\"rtl\"` on the carousel root — the runtime reads that attribute directly (falling back to `<html dir>`). There's no `opts` to configure; `opts` isn't read at all (see [Options](#options)).\n\n```html showLineNumbers\n<div data-slot=\"carousel\" dir=\"rtl\">\n  <div data-slot=\"carousel-content\">\n    <div data-slot=\"carousel-item\">...</div>\n    <div data-slot=\"carousel-item\">...</div>\n    <div data-slot=\"carousel-item\">...</div>\n  </div>\n  <button data-slot=\"carousel-previous\" class=\"rtl:rotate-180\"></button>\n  <button data-slot=\"carousel-next\" class=\"rtl:rotate-180\"></button>\n</div>\n```\n"},
	{page: "table", find: "A table showing actions for each row using a `<DropdownMenu />` component.", repl: "A table showing actions for each row using a dropdown-menu trigger (see the [Dropdown Menu](/docs/components/dropdown-menu) page)."},
	{page: "rtl", find: "```tsx showLineNumbers /dir=\"rtl\"/\n<Popover>\n  <PopoverTrigger>Open</PopoverTrigger>\n  <PopoverContent dir=\"rtl\">\n    <div>Content</div>\n  </PopoverContent>\n</Popover>\n```\n", repl: "```html showLineNumbers /dir=\"rtl\"/\n<button data-slot=\"popover-trigger\" id=\"<k>-trigger\">Open</button>\n<template id=\"<k>-portal\">\n  <div data-slot=\"popover-content\" dir=\"rtl\">\n    <div>Content</div>\n  </div>\n</template>\n```"},
	{page: "rtl", find: "```tsx showLineNumbers /dir=\"rtl\"/\n<Tooltip>\n  <TooltipTrigger>Open</TooltipTrigger>\n  <TooltipContent dir=\"rtl\">\n    <div>Content</div>\n  </TooltipContent>\n</Tooltip>\n```\n", repl: "```html showLineNumbers /dir=\"rtl\"/\n<button data-slot=\"tooltip-trigger\" id=\"<k>-trigger\">Open</button>\n<template id=\"<k>-portal\">\n  <div data-slot=\"tooltip-content\" dir=\"rtl\">\n    <div>Content</div>\n  </div>\n</template>\n```"},
	{page: "carousel", find: "```tsx showLineNumbers /vertical | horizontal/\n<Carousel orientation=\"vertical | horizontal\">\n  <CarouselContent>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n    <CarouselItem>...</CarouselItem>\n  </CarouselContent>\n</Carousel>\n```\n", repl: "```html showLineNumbers /vertical/\n<div data-slot=\"carousel\" data-orientation=\"vertical\">\n  <div data-slot=\"carousel-content\">\n    <div data-slot=\"carousel-item\">...</div>\n    <div data-slot=\"carousel-item\">...</div>\n    <div data-slot=\"carousel-item\">...</div>\n  </div>\n</div>\n```\n\n`dist/js/carousel.js` reads `data-orientation=\"vertical\"` on the root; with no such attribute it falls back to whether the content element carries `flex-col`, and otherwise scrolls horizontally.\n"},
	{page: "item", find: "Use the `asChild` prop to render the item as a link. The hover and focus states will be applied to the anchor element.\n\n<ComponentPreview styleName=\"radix-nova\" name=\"item-link\" />\n\n```tsx showLineNumbers\n<Item asChild>\n  <a href=\"/dashboard\">\n    <ItemMedia variant=\"icon\">\n      <HomeIcon />\n    </ItemMedia>\n    <ItemContent>\n      <ItemTitle>Dashboard</ItemTitle>\n      <ItemDescription>Overview of your account and activity.</ItemDescription>\n    </ItemContent>\n  </a>\n</Item>\n```\n", repl: "shadless has no `asChild` — put `data-slot=\"item\"` on the anchor itself. The hover and focus states apply to the anchor.\n\n<ComponentPreview styleName=\"radix-nova\" name=\"item-link\" />\n\n```html showLineNumbers\n<a data-slot=\"item\" href=\"/dashboard\">\n  <div data-slot=\"item-media\" data-variant=\"icon\">\n    <!-- lucide \"home\" icon -->\n  </div>\n  <div data-slot=\"item-content\">\n    <div data-slot=\"item-title\">Dashboard</div>\n    <p data-slot=\"item-description\">Overview of your account and activity.</p>\n  </div>\n</a>\n```\n"},
	{page: "marker", find: "Turn a marker into a link or button with the `asChild` prop on `Marker`.\n\n<ComponentPreview\n  styleName=\"radix-rhea\"\n  name=\"marker-link-button\"\n  previewClassName=\"h-auto theme-blue\"\n/>\n\n```tsx showLineNumbers\nimport { Marker, MarkerContent } from \"@/components/ui/marker\"\n\nexport function MarkerLinkDemo() {\n  return (\n    <Marker asChild>\n      <a href=\"#\">\n        <MarkerContent>View the pull request</MarkerContent>\n      </a>\n    </Marker>\n  )\n}\n```\n", repl: "Turn a marker into a link or button by putting `data-slot=\"marker\"` on the `<a>` or `<button>` itself — shadless has no `asChild`.\n\n<ComponentPreview\n  styleName=\"radix-rhea\"\n  name=\"marker-link-button\"\n  previewClassName=\"h-auto theme-blue\"\n/>\n\n```html showLineNumbers\n<a data-slot=\"marker\" href=\"#\">\n  <span data-slot=\"marker-content\">View the pull request</span>\n</a>\n```\n"},
	{page: "marker", find: "When a marker links or triggers an action, render it as a real `<button>` or `<a>` with the `asChild` prop so it is focusable and exposes the correct role. The accessible name comes from the marker text.\n\n```tsx showLineNumbers\n<Marker asChild>\n  <a href=\"/files\">\n    <MarkerIcon>\n      <FileTextIcon />\n    </MarkerIcon>\n    <MarkerContent>Explored 4 files</MarkerContent>\n  </a>\n</Marker>\n```\n", repl: "When a marker links or triggers an action, put `data-slot=\"marker\"` on a real `<button>` or `<a>` so it is focusable and exposes the correct role. The accessible name comes from the marker text.\n\n```html showLineNumbers\n<a data-slot=\"marker\" href=\"/files\">\n  <span data-slot=\"marker-icon\"><!-- lucide \"file-text\" icon --></span>\n  <span data-slot=\"marker-content\">Explored 4 files</span>\n</a>\n```\n"},
	{page: "direction", find: "## useDirection\n\nThe `useDirection` hook is used to get the current direction of the application.\n\n```tsx showLineNumbers\nimport { useDirection } from \"@/components/ui/direction\"\n\nfunction MyComponent() {\n  const direction = useDirection()\n  return <div>Current direction: {direction}</div>\n}\n```\n", repl: "## Reading the direction\n\nThere is no `useDirection` hook and no `dist/js/direction.js` — direction is the DOM's own `dir` attribute. Read it the way the runtime itself does (`isRtl` in `dist/shadless.js`): the nearest `[dir]` ancestor, falling back to `<html dir>`.\n\n```js showLineNumbers\nfunction directionOf(el) {\n  var d = el.closest(\"[dir]\")\n  return (d ? d.getAttribute(\"dir\") : document.documentElement.getAttribute(\"dir\")) || \"ltr\"\n}\n```\n"},
}

func applyJsxOverrides(page, raw string) (string, error) {
	out := raw
	for _, o := range jsxOverrides {
		if o.page != page {
			continue
		}
		if !strings.Contains(out, o.find) {
			return "", fmt.Errorf("%s: jsx override anchor not found — re-anchor against the new upstream content: %q", page, o.find)
		}
		out = strings.Replace(out, o.find, o.repl, 1)
	}
	return out, nil
}
