//! Port of pipeline/audit_boundary.go — categorizes every file in the repo
//! as PROGRAMMATIC (regenerated by tools) vs TOOL SOURCE (hand-written code
//! that owns those outputs) vs HAND-AUTHORED, and surfaces the explicit LLM
//! PATCH POINTS inside tool source.
//!
//! The path patterns ARE the source of truth. Patterns are matched
//! first-match-wins and the order is load-bearing: a catch-all placed before
//! a specific rule shadows it — a real bug this file already carried once, so
//! the ordering is asserted by a test rather than left to reading.

use regex::Regex;
use serde::Deserialize;
use serde_json::Value;
use std::collections::HashMap;
use std::path::Path;
use std::sync::{Mutex, OnceLock};

/// A classification pattern. Exactly one of tool/note/owner is set, matching
/// the three kinds. `matches` unifies Go's re/match split (statics cannot
/// call Regex::new, so patterns compile lazily through re_cache).
struct BoundaryPattern {
    matches: Box<dyn Fn(&str) -> bool + Send + Sync>,
    tool: &'static str,
    source: &'static str,
    note: &'static str,
    owner: &'static str,
}

impl BoundaryPattern {
    fn test(&self, path: &str) -> bool {
        (self.matches)(path)
    }
}

fn re_cache(pat: &'static str) -> &'static Regex {
    static CACHE: OnceLock<Mutex<HashMap<&'static str, &'static Regex>>> = OnceLock::new();
    let mut g = CACHE.get_or_init(Default::default).lock().unwrap();
    *g.entry(pat).or_insert_with(|| Box::leak(Box::new(Regex::new(pat).unwrap())))
}

fn one_of(paths: &'static [&'static str]) -> Box<dyn Fn(&str) -> bool + Send + Sync> {
    Box::new(move |p: &str| paths.contains(&p))
}

fn prefix_suffix(
    prefix: &'static str,
    suffixes: &'static [&'static str],
) -> Box<dyn Fn(&str) -> bool + Send + Sync> {
    Box::new(move |p: &str| {
        if !p.starts_with(prefix) {
            return false;
        }
        if suffixes.is_empty() {
            return true;
        }
        suffixes.iter().any(|s| p.ends_with(s))
    })
}

fn rtl_variant(p: &str) -> bool {
    crate::emit::build_rtl::rtl_page_lang(p).is_some()
}

fn tool_source_patterns() -> &'static [BoundaryPattern] {
    static T: OnceLock<Vec<BoundaryPattern>> = OnceLock::new();
    T.get_or_init(|| {
        vec![
            BoundaryPattern {
                matches: Box::new(|p: &str| re_cache(r"^pipeline/.*\.go$").is_match(p)),
                tool: "",
                source: "",
                note: "pipeline/*.go — Go-era sources; only the port-parity probes remain (pipeline/probe/json-go) — the engine itself is pipeline/src/**/*.rs",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| re_cache(r"^pipeline/src/.*\.rs$").is_match(p)),
                tool: "",
                source: "",
                note: "pipeline/src/** — the Rust engine (runner, converter, emitters, gates, tools)",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| re_cache(r"^tools/.*\.mjs$").is_match(p)),
                tool: "",
                source: "",
                note: "tools/*.mjs — JS test harnesses + recorders (unit, contracts, browser-shell, fs-record, prettier-batch); the builder gates moved into the Rust engine",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| re_cache(r"^src/emitter/.*\.mjs$").is_match(p)),
                tool: "",
                source: "",
                note: "src/emitter/*.mjs — the aligned JS twin of the rust emit (the emit node, this engine, builds dist); unit-tested via tools/unit/emitter.mjs",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| re_cache(r"^src/docs/.*\.mjs$").is_match(p)),
                tool: "",
                source: "",
                note: "src/docs/*.mjs — JSX/runtime used by the MDX compile step (ComponentPreview, code-copy/view-code/rtl handlers, theme pre-paint, etc.)",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| re_cache(r"^src/runtime/.*\.(mjs|js)$").is_match(p)),
                tool: "",
                source: "",
                note: "src/runtime/*.mjs|js — interactive runtime copied into dist/ as shadless.js",
                owner: "",
            },
            BoundaryPattern {
                matches: one_of(&["src/tags.mjs"]),
                tool: "",
                source: "",
                note: "src/tags.mjs — tag normalization shared by converter/emitter/css",
                owner: "",
            },
        ]
    })
}

fn programmatic_patterns() -> &'static [BoundaryPattern] {
    static T: OnceLock<Vec<BoundaryPattern>> = OnceLock::new();
    T.get_or_init(|| {
        vec![
            // IR (converter)
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("generated/ir/") && p.ends_with(".json")),
                tool: "pipeline/src/convert/mod.rs",
                source: "apps/v4/registry/bases/radix/ui/*.tsx",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("generated/docs-upstream/")),
                tool: "pipeline/src/tools/docs_upstream_mirror.rs",
                source: "apps/v4/content/docs/components/radix/* + rtl/index.mdx + utils/{shimmer,scroll-fade}.mdx",
                note: "",
                owner: "",
            },
            // dist/components — emitter + build-rtl + demo (multi-source)
            BoundaryPattern {
                matches: Box::new(|p: &str| {
                    p.starts_with("dist/components/")
                        && p.ends_with(".html")
                        && !rtl_variant(p)
                        && !p.ends_with("-demo.html")
                }),
                tool: "./build/pipeline example-fixture (per-tier fixture)",
                source: "generated/ir/*.json + the per-tier fixture families (oracle/example_fixture.rs)",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("dist/components/") && rtl_variant(p)),
                tool: "pipeline/src/emit/build_rtl.rs",
                source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/src/tools/rtl_dict.rs)",
                note: "",
                owner: "",
            },
            // docs/demos — build-rtl writes here too (so the host page can
            // serve the iframes even before docs-build copies them into
            // docs/site/).
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("docs/demos/") && rtl_variant(p)),
                tool: "pipeline/src/emit/build_rtl.rs",
                source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/src/tools/rtl_dict.rs)",
                note: "",
                owner: "",
            },
            // example-oracle renders each upstream example with React and
            // writes the page, and example-fixture wires the ones carrying a
            // kernel family. Both record what they wrote — ownership is read
            // from those manifests rather than guessed from the path.
            BoundaryPattern {
                matches: Box::new(in_manifest("docs/example-fixture-targets.json", "name")),
                tool: "pipeline/src/oracle/example_fixture.rs",
                source: "the React oracle render, with kernel-family JS wired in",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(in_manifest("docs/example-oracle.json", "out")),
                tool: "pipeline/src/oracle/example_oracle.rs",
                source: "examples/radix/<name>.tsx, rendered with real React",
                note: "",
                owner: "",
            },
            // dist CSS / JS — tailwind + copy
            BoundaryPattern {
                matches: one_of(&[
                    "dist/out.css",
                    "dist/globals.css",
                    "dist/shadless.css",
                    "dist/shadless-core.css",
                ]),
                tool: "npx @tailwindcss/cli (via make demo / make docs)",
                source: "dist/components/*.html + shadless CSS fixes",
                note: "",
                owner: "",
            },
            // J2 product surface — per-component @apply sources + tokens +
            // compiled
            BoundaryPattern {
                matches: prefix_suffix("dist/css/", &[".css"]),
                tool: "pipeline/src/emit/demo.rs (parts) + pipeline/src/emit/product_css.rs (tokens)",
                source: "generated/ir/*.json + probes/h4/globals.css",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: one_of(&[
                    "dist/shadless.product.css",
                    "dist/shadless.full.css",
                    "dist/shadless.full.min.css",
                ]),
                tool: "pipeline/src/emit/product_css.rs + pipeline/src/emit/tw.rs",
                source: "dist/css/* (tokens + component parts + fixes)",
                note: "",
                owner: "",
            },
            // J4: server-stack template macros — regenerated from IR
            BoundaryPattern {
                matches: one_of(&["dist/shadless.js", "dist/shadless.min.js"]),
                tool: "./build/pipeline build-js",
                source: "vendor/radix-kernel.iife.js + src/runtime/core.js",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| {
                    (p.starts_with("dist/js/") || p.starts_with("dist/esm/"))
                        && re_cache(r"\.(m?js|d\.ts)$").is_match(p)
                }),
                tool: "./build/pipeline build-js",
                source: "src/runtime/core.js + src/runtime/components/*.js + src/runtime/shadless.d.ts + vendor/*.iife.js",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: one_of(&["dist/demo-index.html"]),
                tool: "pipeline/src/emit/demo.rs",
                source: "per-tier IR list (built into demo.mjs)",
                note: "",
                owner: "",
            },
            // docs/site — the Zola site. content/ + static/ are docs-build
            // output; public/ is zola build output; themes/vitezola is
            // vendored.
            BoundaryPattern {
                matches: Box::new(|p: &str| {
                    p.starts_with("docs/site/content/") || p.starts_with("docs/site/static/")
                }),
                tool: "pipeline/src/tools/docs_build.rs (zola markdown + copied dist/demos)",
                source: ".upstream mdx + docs/content/*.mdx + dist/** + docs/demos/**",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("docs/site/public/")),
                tool: "zola build --root docs/site",
                source: "docs/site/content/** + docs/site/static/** + docs/site/themes/vitezola",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("docs/site/themes/vitezola/")),
                tool: "vendored (github.com/newlix/vitezola — see docs/site/themes/vitezola/ORIGIN.txt)",
                source: "the vitezola release tree, stripped of its demo content",
                note: "",
                owner: "",
            },
            BoundaryPattern {
                matches: one_of(&["build/rtl-langs.json"]),
                tool: "pipeline/src/emit/build_rtl.rs",
                source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/src/tools/rtl_dict.rs)",
                note: "",
                owner: "",
            },
            // catalog + reports
            BoundaryPattern {
                matches: one_of(&["docs/catalog.json"]),
                tool: "pipeline/src/tools/docs_catalog.rs",
                source: ".upstream/.../components/*/*.mdx + dist/components state",
                note: "",
                owner: "",
            },
        ]
    })
}

fn hand_authored_patterns() -> &'static [BoundaryPattern] {
    static T: OnceLock<Vec<BoundaryPattern>> = OnceLock::new();
    T.get_or_init(|| {
        vec![
            // Vendor files (vendored from upstream release artifacts)
            BoundaryPattern {
                matches: one_of(&[
                    "vendor/radix-kernel.iife.js",
                    "vendor/embla-carousel.iife.js",
                ]),
                tool: "",
                source: "",
                note: "",
                owner: "human (vendor)",
            },
            // what neither manifest claims: the examples no oracle can bundle
            // (external deps, recorded in the golden exemptions)
            BoundaryPattern {
                matches: Box::new(|p: &str| p.starts_with("docs/demos/") && !p.contains("-rtl")),
                tool: "",
                source: "",
                note: "",
                owner: "human (examples the oracle cannot bundle — see the golden exemptions)",
            },
            // Guide source content (consumed by docs-build)
            BoundaryPattern {
                matches: prefix_suffix("docs/content/", &[".mdx"]),
                tool: "",
                source: "",
                note: "",
                owner: "human (guide source — compiled by docs-build into docs/site/)",
            },
            // The Zola site shell — hand-authored sources around the vendored
            // theme
            BoundaryPattern {
                matches: one_of(&["docs/site/config.toml"]),
                tool: "",
                source: "",
                note: "",
                owner: "human (site shell — Zola config, nav, search)",
            },
            BoundaryPattern {
                matches: prefix_suffix("docs/site/templates/", &[".html"]),
                tool: "",
                source: "",
                note: "",
                owner: "human (site components — the demo card the content transform emits)",
            },
            BoundaryPattern {
                matches: prefix_suffix("docs/site/sass/", &[".scss", ".sass"]),
                tool: "",
                source: "",
                note: "",
                owner: "human (site CSS — demo cards, demo-missing, linked-card)",
            },
            BoundaryPattern {
                matches: one_of(&["docs/content-map.json"]),
                tool: "",
                source: "",
                note: "",
                owner: "human (FT7 build state)",
            },
            // Pin tracking
            BoundaryPattern {
                matches: one_of(&["src/registry/pin.json"]),
                tool: "",
                source: "",
                note: "",
                owner: "pipeline upstream (re-pin) / human (vendor re-hash via ./build/pipeline pin --force)",
            },
            // Docs / orchestration (mix of programmatic generation and human
            // prose)
            BoundaryPattern {
                matches: Box::new(|p: &str| {
                    matches!(
                        p,
                        "Makefile" | "README.md" | "UPGRADING.md" | "package.json"
                            | ".gitignore" | "package-lock.json"
                    ) || re_cache(r"^FINDING-.*\.md$").is_match(p)
                }),
                tool: "",
                source: "",
                note: "",
                owner: "human (orchestration + narrative)",
            },
            // Probe fixtures — used by emit/demo as references, but
            // hand-written
            BoundaryPattern {
                matches: prefix_suffix("probes/", &[]),
                tool: "",
                source: "",
                note: "",
                owner: "human (test fixtures; some consumed by pipeline/src/emit/demo.rs)",
            },
        ]
    })
}

/// A curated region inside tool source where a human is expected to
/// intervene. Not regenerated — the seam between script and human.
struct LlmPatchPoint {
    file: &'static str,
    lines: &'static str,
    what: &'static str,
}

static LLM_PATCH_POINTS: &[LlmPatchPoint] = &[
    LlmPatchPoint {
        file: "pipeline/src/emit/build_rtl.rs",
        lines: "32-37",
        what: "PERSIAN translations dict — 4 keys × 2 alerts for alert-rtl only. Upstream ships en/ar/he; Persian isn't in upstream so hand-coded. When upstream adds a new language, add it here (or generalize to read from upstream).",
    },
    LlmPatchPoint {
        file: "pipeline/src/emit/demo.rs",
        lines: "~127-230",
                what: "Per-tier HTML fixtures (dialogDemoHtml, fieldDemoHtml, etc.) — kernel/trivial-js components get static HTML hand-written here; consumed by pipeline/src/emit/demo.rs.",
    },
    LlmPatchPoint {
        file: "docs/demos/",
        lines: "(directory)",
        what: "Almost all of this is generated: example-oracle writes 226 pages from the React render, example-fixture 105 more with kernel-family JS wired in, build-rtl the *-rtl-{he,en,fa} variants. What is left hand-authored is the message-scroller family, whose examples the oracle cannot bundle (external deps) and which is recorded in the golden exemptions and in interactivity-sweep's KNOWN_DEAD.",
    },
];

// ---------------------------------------------------------------- scan

#[derive(Clone, Default, Debug)]
pub struct Classification {
    pub path: String,
    pub kind: String, // programmatic | tool-source | hand-authored | unknown
    pub tool: String,
    pub source: String,
    pub note: String,
    pub owner: String,
}

/// The grouping key for a classification: the tool that owns it, the note
/// describing it, or its owner.
impl Classification {
    fn label(&self) -> &str {
        if !self.tool.is_empty() {
            &self.tool
        } else if !self.note.is_empty() {
            &self.note
        } else if !self.owner.is_empty() {
            &self.owner
        } else {
            ""
        }
    }
}

pub fn classify_path(path: &str) -> Classification {
    for p in programmatic_patterns() {
        if p.test(path) {
            return Classification {
                path: path.to_string(),
                kind: "programmatic".to_string(),
                tool: p.tool.to_string(),
                source: p.source.to_string(),
                note: String::new(),
                owner: String::new(),
            };
        }
    }
    for p in tool_source_patterns() {
        if p.test(path) {
            return Classification {
                path: path.to_string(),
                kind: "tool-source".to_string(),
                note: p.note.to_string(),
                ..Classification::default()
            };
        }
    }
    for p in hand_authored_patterns() {
        if p.test(path) {
            return Classification {
                path: path.to_string(),
                kind: "hand-authored".to_string(),
                owner: p.owner.to_string(),
                ..Classification::default()
            };
        }
    }
    Classification {
        path: path.to_string(),
        kind: "unknown".to_string(),
        ..Classification::default()
    }
}

/// dist/ is deliberately NOT skipped — dist/components/*.html is git-tracked
/// and is the live library output. tools/contracts/out IS skipped: those are
/// runtime oracle artifacts, not repo source.
const AUDIT_SKIP: [&str; 4] = [".git", "node_modules", ".upstream", "tools/contracts/out"];

pub fn audit_should_skip(rel: &str) -> bool {
    for s in AUDIT_SKIP {
        if s.contains('/') {
            // path-prefix match
            if rel == s || rel.starts_with(&format!("{}/", s)) {
                return true;
            }
            continue;
        }
        if rel.split('/').any(|seg| seg == s) {
            return true;
        }
    }
    false
}

pub fn audit_walk(root: &Path) -> Result<Vec<String>, String> {
    let mut out: Vec<String> = Vec::new();
    let root_buf = root.canonicalize().unwrap_or_else(|_| root.to_path_buf());
    for e in walkdir::WalkDir::new(&root_buf)
        .into_iter()
        .filter_entry(|entry| {
            // prune a skipped directory the way filepath.SkipDir did: the
            // entry itself is matched on its repo-relative path
            let rel = entry
                .path()
                .strip_prefix(&root_buf)
                .map(|r| r.to_string_lossy().into_owned())
                .unwrap_or_default();
            rel.is_empty() || !audit_should_skip(&rel)
        })
    {
        let Ok(e) = e else { continue }; // an unreadable directory is skipped, as readdirSync's catch did
        if !e.file_type().is_dir() {
            let rel = match e.path().strip_prefix(&root_buf) {
                Ok(r) => r.to_string_lossy().into_owned(),
                Err(_) => continue,
            };
            if rel.is_empty() {
                continue;
            }
            out.push(rel);
        }
    }
    out.sort();
    Ok(out)
}

// ------------------------------------------------------- drift detection

/// Finds tool-generated files MODIFIED relative to HEAD. Untracked files are
/// NOT drift: they are the normal state after `make build`.
pub fn detect_drift(root: &Path, programmatic: &[Classification]) -> Vec<Classification> {
    let modified = git_paths(
        root,
        "--untracked-files=no",
        |x, y| x == b'M' || y == b'M' || x == b'D' || y == b'D',
    );
    programmatic
        .iter()
        .filter(|c| modified.contains_key(&c.path))
        .cloned()
        .collect()
}

/// Runs git status --porcelain and returns the paths whose XY status
/// satisfies keep. A git that is not available yields nothing, as the JS did.
fn git_paths(root: &Path, untracked: &str, keep: fn(u8, u8) -> bool) -> HashMap<String, bool> {
    let mut out = HashMap::new();
    let Ok(b) = std::process::Command::new("git")
        .args(["status", "--porcelain", untracked])
        .current_dir(root)
        .output()
    else {
        return out;
    };
    if !b.status.success() {
        return out;
    }
    for line in String::from_utf8_lossy(&b.stdout).lines() {
        let lb = line.as_bytes();
        if lb.len() < 4 {
            continue;
        }
        if !keep(lb[0], lb[1]) {
            continue;
        }
        let mut rest = &line[3..];
        if let Some(i) = rest.find(" -> ") {
            rest = &rest[i + 4..]; // a rename reports the destination
        }
        out.insert(rest.trim_matches('"').to_string(), true);
    }
    out
}

/// Lists untracked and staged-added paths — everything new since HEAD.
fn detect_new_files(root: &Path) -> Vec<String> {
    let paths = git_paths(root, "--untracked-files=all", |x, y| {
        (x == b'?' && y == b'?') || x == b'A'
    });
    let mut out: Vec<String> = paths
        .into_keys()
        .filter(|p| !p.ends_with('/')) // git lists directories with a trailing slash
        .collect();
    out.sort();
    out
}

// ------------------------------------------------------- discover mode

struct HeuristicHint {
    re: &'static str,
    kind: &'static str,
    tool: &'static str,
    source: &'static str,
    note: &'static str,
    owner: &'static str,
}

fn heuristic_hints() -> &'static [HeuristicHint] {
    static HINTS: OnceLock<Vec<HeuristicHint>> = OnceLock::new();
    HINTS.get_or_init(|| {
        vec![
            HeuristicHint {
                re: r"^dist/components/[^/]+-rtl-(en|he|fa)\.html$",
                kind: "programmatic",
                tool: "pipeline/src/emit/build_rtl.rs",
                source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/src/tools/rtl_dict.rs)",
                note: "",
                owner: "",
            },
            HeuristicHint {
                re: r"^docs/demos/[^/]+-rtl-(en|he|fa)\.html$",
                kind: "programmatic",
                tool: "pipeline/src/emit/build_rtl.rs",
                source: "src/registry/rtl-translations.json (lifted from examples/aria by pipeline/src/tools/rtl_dict.rs)",
                note: "",
                owner: "",
            },
            HeuristicHint {
                re: r"^(docs/demos|dist/components)/[^/]+-demo\.html$",
                kind: "programmatic",
                tool: "pipeline/src/oracle/example_oracle.rs",
                source: "examples/radix/<name>-demo.tsx, rendered with real React",
                note: "",
                owner: "",
            },
            HeuristicHint {
                re: r"^dist/glue/",
                kind: "programmatic",
                tool: "pipeline/src/emit/demo.rs",
                source: "src/kernel/*-glue.js",
                note: "",
                owner: "",
            },
            // Catch-all: any HTML under dist/ is a build artifact. The
            // specific rules above catch the known subdirs; this handles a
            // new one that nobody has added a rule for yet.
            HeuristicHint {
                re: r"^dist/.+\.html$",
                kind: "programmatic",
                tool: "./build/pipeline example-fixture (per-tier fixture)",
                source: "generated/ir/*.json + the per-tier fixture families",
                note: "",
                owner: "",
            },
            HeuristicHint {
                re: r"^docs/site/(content|static)/",
                kind: "programmatic",
                tool: "pipeline/src/tools/docs_build.rs",
                source: "upstream mdx + dist/** + docs/demos/**",
                note: "",
                owner: "",
            },
            HeuristicHint {
                re: r"^generated/ir/[^/]+\.json$",
                kind: "programmatic",
                tool: "pipeline/src/convert/mod.rs",
                source: "apps/v4/registry/bases/radix/ui/*.tsx",
                note: "",
                owner: "",
            },
            HeuristicHint {
                re: r"^tools/[^/]+\.mjs$",
                kind: "tool-source",
                tool: "",
                source: "",
                note: "pipeline orchestrator + builder tool",
                owner: "",
            },
            HeuristicHint {
                re: r"^scripts/[^/]+\.(sh|js|mjs)$",
                kind: "tool-source",
                tool: "",
                source: "",
                note: "scripts/*.sh|js|mjs — ad-hoc scripts; consider promoting to tools/ if used by Makefile",
                owner: "",
            },
            HeuristicHint {
                re: r"^src/emitter/[^/]+\.mjs$",
                kind: "tool-source",
                tool: "",
                source: "",
                note: "src/emitter — IR → dist/components + slot CSS",
                owner: "",
            },
            HeuristicHint {
                re: r"^src/docs/[^/]+\.mjs$",
                kind: "tool-source",
                tool: "",
                source: "",
                note: "src/docs — JSX runtime used by MDX compile",
                owner: "",
            },
            HeuristicHint {
                re: r"^src/runtime/[^/]+\.(mjs|js)$",
                kind: "tool-source",
                tool: "",
                source: "",
                note: "src/runtime — interactive runtime (copied to dist/shadless.js)",
                owner: "",
            },
            HeuristicHint {
                re: r"^vendor/",
                kind: "hand-authored",
                tool: "",
                source: "",
                note: "",
                owner: "human (vendor — manually vendored from upstream)",
            },
            HeuristicHint {
                re: r"^probes/",
                kind: "hand-authored",
                tool: "",
                source: "",
                note: "",
                owner: "human (test fixture)",
            },
            HeuristicHint {
                re: r"^docs/demos/",
                kind: "hand-authored",
                tool: "",
                source: "",
                note: "",
                owner: "human (remaining hand-written demos only — all programmatic demos come from example-oracle)",
            },
            HeuristicHint {
                re: r"^docs/content/[^/]+\.mdx$",
                kind: "hand-authored",
                tool: "",
                source: "",
                note: "",
                owner: "human (guide source — compiled by docs-build)",
            },
            HeuristicHint {
                re: r"^src/registry/pin\.json$",
                kind: "hand-authored",
                tool: "",
                source: "",
                note: "",
                owner: "human (commit hash + vendor SHA256)",
            },
        ]
    })
}

#[derive(Clone, Default, Debug)]
pub struct Suggestion {
    pub method: String,
    pub confidence: f64,
    pub kind: String,
    pub tool: String,
    pub source: String,
    pub note: String,
    pub owner: String,
    pub sampled: usize,
    pub total: usize,
}

/// Looks at files in the SAME DIRECTORY (not the whole subtree — that would
/// overweight huge dirs like docs/site/) that already match a pattern, and
/// proposes the dominant category.
pub fn suggest_from_siblings(
    new_path: &str,
    all: &[String],
    by_path: &HashMap<String, Classification>,
) -> Option<Suggestion> {
    let dir = parent_dir(new_path);
    let mut siblings: Vec<&Classification> = Vec::new();
    let mut matched: Vec<&Classification> = Vec::new();
    for p in all {
        if p == new_path || parent_dir(p) != dir {
            continue;
        }
        let c = &by_path[p]; // caller supplies every path's classification
        siblings.push(c);
        if !c.kind.is_empty() && c.kind != "unknown" {
            matched.push(c);
        }
    }
    if matched.is_empty() {
        return None;
    }
    let mut counts: HashMap<(&str, &str), i64> = HashMap::new();
    for m in &matched {
        *counts.entry((m.kind.as_str(), m.label())).or_insert(0) += 1;
    }
    // deterministic winner: highest count, then lexical
    let mut keys: Vec<(&str, &str)> = counts.keys().copied().collect();
    keys.sort();
    let mut best = keys[0];
    let mut best_n = -1i64;
    for k in &keys {
        if counts[k] > best_n {
            best = *k;
            best_n = counts[k];
        }
    }
    let mut s = Suggestion {
        method: "sibling".to_string(),
        kind: best.0.to_string(),
        confidence: best_n as f64 / siblings.len() as f64,
        sampled: matched.len(),
        total: siblings.len(),
        ..Suggestion::default()
    };
    match s.kind.as_str() {
        "programmatic" => s.tool = best.1.to_string(),
        "tool-source" => s.note = best.1.to_string(),
        "hand-authored" => s.owner = best.1.to_string(),
        _ => {}
    }
    Some(s)
}

pub fn parent_dir(p: &str) -> String {
    match p.rfind('/') {
        Some(i) => p[..i + 1].to_string(),
        None => String::new(),
    }
}

pub fn suggest_from_heuristics(new_path: &str) -> Option<Suggestion> {
    for h in heuristic_hints() {
        if re_cache(h.re).is_match(new_path) {
            return Some(Suggestion {
                method: "heuristic".to_string(),
                confidence: 0.8,
                kind: h.kind.to_string(),
                tool: h.tool.to_string(),
                source: h.source.to_string(),
                note: h.note.to_string(),
                owner: h.owner.to_string(),
                ..Suggestion::default()
            });
        }
    }
    None
}

fn run_discover_mode(root: &Path, all: &[String], by_path: &HashMap<String, Classification>) {
    let new_files = detect_new_files(root);
    if new_files.is_empty() {
        println!("No new files detected in git working tree.");
        return;
    }
    println!(
        "Discovered {} new file{} (untracked + added since HEAD):\n",
        new_files.len(),
        plural(new_files.len())
    );
    let mut matched: Vec<Classification> = Vec::new();
    let mut unmatched: Vec<String> = Vec::new();
    for p in &new_files {
        if let Some(c) = by_path.get(p) {
            if c.kind != "unknown" {
                matched.push(c.clone());
                continue;
            }
        }
        unmatched.push(p.clone());
    }
    if !matched.is_empty() {
        println!("ALREADY CLASSIFIED (matches existing pattern)");
        println!("{}", "-".repeat(72));
        for m in &matched {
            println!("  [{}] {}", m.kind, m.path);
        }
        println!();
    }
    if unmatched.is_empty() {
        return;
    }
    println!("UNCLASSIFIED (needs a new pattern)");
    println!("{}", "-".repeat(72));
    for p in &unmatched {
        println!("  {}", p);
        let sib = suggest_from_siblings(p, all, by_path);
        if let Some(s) = &sib {
            println!(
                "    sibling-based: {}% confidence ({} siblings match)",
                (s.confidence * 100.0 + 0.5) as i64,
                s.sampled
            );
            println!("      kind:  {}", s.kind);
            print_if("      tool:  ", &s.tool);
            print_if("      note:  ", &s.note);
            print_if("      owner: ", &s.owner);
        }
        let heur = suggest_from_heuristics(p);
        if let Some(s) = &heur {
            println!(
                "    heuristic: {}% confidence",
                (s.confidence * 100.0 + 0.5) as i64
            );
            println!("      kind:  {}", s.kind);
            print_if("      tool:  ", &s.tool);
            print_if("      source: ", &s.source);
            print_if("      note:  ", &s.note);
            print_if("      owner: ", &s.owner);
        }
        if sib.is_none() && heur.is_none() {
            println!("    NO SUGGESTION — needs manual categorization");
        }
        println!();
    }
    println!("SUGGESTED PATTERN ADDITIONS (copy-paste into src/gates/audit_boundary.rs):");
    println!("{}", "-".repeat(72));
    for p in &unmatched {
        let sib = suggest_from_siblings(p, all, by_path);
        let use_ = match suggest_from_heuristics(p) {
            Some(h) => Some(h),
            None => sib,
        };
        let Some(use_) = use_ else { continue };
        if !use_.tool.is_empty() {
            println!(
                "  {{match: func(p string) bool {{ /* {} */ }}, tool: {:?}, source: {:?}}},",
                p, use_.tool, use_.source
            );
        } else if !use_.note.is_empty() {
            println!(
                "  {{match: func(p string) bool {{ /* {} */ }}, note: {:?}}},",
                p, use_.note
            );
        } else {
            println!(
                "  {{match: func(p string) bool {{ /* {} */ }}, owner: {:?}}},",
                p, use_.owner
            );
        }
    }
}

fn print_if(label: &str, v: &str) {
    if !v.is_empty() {
        println!("{}{}", label, v);
    }
}

fn plural(n: usize) -> &'static str {
    if n == 1 {
        ""
    } else {
        "s"
    }
}

// ---------------------------------------------------------------- output

/// Group preserves first-appearance order, which is what makes the report
/// stable between runs (a Go map would reshuffle the sections).
struct Group {
    order: Vec<String>,
    items: HashMap<String, Vec<String>>,
}

fn group_by(cs: &[Classification], key: impl Fn(&Classification) -> String) -> Group {
    let mut g = Group {
        order: Vec::new(),
        items: HashMap::new(),
    };
    for c in cs {
        let k = key(c);
        if !g.items.contains_key(&k) {
            g.order.push(k.clone());
        }
        g.items.entry(k).or_default().push(c.path.clone());
    }
    g
}

impl Group {
    fn print(&self) {
        for k in &self.order {
            let paths = &self.items[k];
            println!();
            println!("[{}]  ({} file{})", k, paths.len(), plural(paths.len()));
            for (i, p) in paths.iter().enumerate() {
                if i == 8 {
                    println!("  …and {} more", paths.len() - 8);
                    break;
                }
                println!("  {}", p);
            }
        }
    }
}

pub fn run_audit_boundary(args: &[String]) -> i32 {
    let root = match std::env::current_dir() {
        Ok(r) => r,
        Err(e) => {
            eprintln!("pipeline: {}", e);
            return 1;
        }
    };
    let Ok(all) = audit_walk(&root) else {
        eprintln!("pipeline: audit walk failed");
        return 1;
    };
    let mut classified: Vec<Classification> = Vec::with_capacity(all.len());
    let mut by_path: HashMap<String, Classification> = HashMap::with_capacity(all.len());
    for p in &all {
        let c = classify_path(p);
        by_path.insert(p.clone(), c.clone());
        classified.push(c);
    }

    let has = |f: &str| args.iter().any(|a| a == f);
    if has("discover") {
        run_discover_mode(&root, &all, &by_path);
        return 0;
    }

    let mut programmatic: Vec<Classification> = Vec::new();
    let mut tool_source: Vec<Classification> = Vec::new();
    let mut hand_authored: Vec<Classification> = Vec::new();
    let mut unknown: Vec<Classification> = Vec::new();
    for c in &classified {
        match c.kind.as_str() {
            "programmatic" => programmatic.push(c.clone()),
            "tool-source" => tool_source.push(c.clone()),
            "hand-authored" => hand_authored.push(c.clone()),
            _ => unknown.push(c.clone()),
        }
    }
    let drift = detect_drift(&root, &programmatic);

    if has("--strict") {
        #[derive(serde::Serialize)]
        struct DriftRow<'a> {
            path: &'a str,
            tool: &'a str,
        }
        let rows: Vec<DriftRow> = drift
            .iter()
            .map(|d| DriftRow {
                path: &d.path,
                tool: &d.tool,
            })
            .collect();
        let out = serde_json::json!({
            "programmatic": programmatic.len(),
            "tool_source": tool_source.len(),
            "hand_authored": hand_authored.len(),
            "unknown": unknown.len(),
            "llm_patch_points": LLM_PATCH_POINTS.len(),
            "drift": rows,
        });
        // Go json.MarshalIndent(v, "", "  ") — 2-space pretty
        println!("{}", serde_json::to_string_pretty(&out).unwrap());
        if drift.is_empty() {
            return 0;
        }
        return 1;
    }

    println!("PROGRAMMATIC ZONE — regenerated by tools on `make build`");
    println!("{}", "=".repeat(72));
    let by_tool = group_by(&programmatic, |c| {
        if c.tool.is_empty() {
            "(unknown tool)".to_string()
        } else {
            c.tool.clone()
        }
    });
    by_tool.print();
    print!("\n\n\n\n");
    println!("HAND-AUTHORED ZONE — LLM/human edits expected, no script owns them");
    println!("{}", "=".repeat(72));
    let by_owner = group_by(&hand_authored, |c| {
        if c.owner.is_empty() {
            "(unowned)".to_string()
        } else {
            c.owner.clone()
        }
    });
    by_owner.print();
    print!("\n\n");
    println!("TOOL SOURCE — hand-written code that owns the PROGRAMMATIC ZONE");
    println!("{}", "=".repeat(72));
    for p in tool_source_patterns() {
        println!();
        println!("[{}]", p.note);
        let matches: Vec<&String> = tool_source
            .iter()
            .filter(|c| p.test(&c.path))
            .map(|c| &c.path)
            .collect();
        for (i, m) in matches.iter().enumerate() {
            if i == 8 {
                println!("  …and {} more", matches.len() - 8);
                break;
            }
            println!("  {}", m);
        }
    }
    print!("\n\n");
    println!("LLM PATCH POINTS — explicit hand-coded regions inside tool source");
    println!("{}", "=".repeat(72));
    for p in LLM_PATCH_POINTS {
        println!();
        let mut loc = p.file.to_string();
        if !p.lines.is_empty() {
            loc += &format!(":{}", p.lines);
        }
        println!("[{}]", loc);
        println!("  {}", p.what);
    }
    print!("\n\n");
    println!("DRIFT — tool-generated files with uncommitted changes");
    println!("{}", "=".repeat(72));
    println!(
        r#"(Tool-generated file is "drift" if git status shows it as"#
    );
    println!(" modified. NOTE: this is noisy right after `make build` — every");
    println!(" regenerated file appears as drift until committed. Run");
    println!(" `git status` to see if drift is from a fresh build vs a");
    println!(" manual edit. For CI gating, use --strict mode.)");
    if drift.is_empty() {
        println!();
        println!("(none)");
    } else if drift.len() > 30 {
        println!();
        println!(
            "({} files — showing first 30; run `git status` for full list)",
            drift.len()
        );
        for d in drift.iter().take(30) {
            println!("  {}  ({})", d.path, d.tool);
        }
    } else {
        println!();
        for d in &drift {
            println!("  {}  ({})", d.path, d.tool);
        }
    }
    print!("\n\n");
    println!("SUMMARY");
    println!("{}", "=".repeat(72));
    println!(
        "  programmatic: {} files (regenerated by {} tools)",
        programmatic.len(),
        by_tool.order.len()
    );
    println!(
        "  tool source: {} files (hand-written code that owns the PROGRAMMATIC zone)",
        tool_source.len()
    );
    println!(
        "  hand-authored: {} files (in {} categories)",
        hand_authored.len(),
        by_owner.order.len()
    );
    println!("  unknown: {} files (no pattern matched)", unknown.len());
    println!("  LLM patch points: {}", LLM_PATCH_POINTS.len());
    println!("  drift: {}", drift.len());
    if !unknown.is_empty() {
        println!();
        println!("UNKNOWN files (no pattern matched — add to programmaticPatterns or handAuthoredPatterns):");
        for (i, u) in unknown.iter().enumerate() {
            if i == 20 {
                println!("  …and {} more", unknown.len() - 20);
                break;
            }
            println!("  {}", u.path);
        }
    }
    0
}

// inManifest matches a path a tool recorded as its own output.
//
// A tool that writes a manifest is telling you what it owns; reading that is
// both correct today and correct after the tool's coverage changes. `field`
// is the key holding the path or the page name — example-oracle records
// {name, out} and example-fixture records {name}. A manifest that cannot be
// read matches nothing, so a missing file degrades to "unknown" rather than
// to a false claim of ownership. Only a SUCCESSFUL read is remembered.
fn in_manifest(
    manifest: &'static str,
    field: &'static str,
) -> impl Fn(&str) -> bool + Send + Sync {
    static OWNED: OnceLock<Mutex<HashMap<&'static str, HashMap<String, bool>>>> = OnceLock::new();
    let owned_store = OWNED.get_or_init(Default::default);
    move |p: &str| {
        let mut guard = owned_store.lock().unwrap();
        if !guard.contains_key(manifest) {
            let Ok(cwd) = std::env::current_dir() else {
                return false;
            };
            // The root is found by walking up rather than taken from the cwd,
            // so this behaves the same whether it runs from the repo root or
            // from a test working directory.
            let Some(root) = find_repo_root_from(&cwd) else {
                return false;
            };
            let Ok(b) = std::fs::read_to_string(root.join(manifest)) else {
                return false;
            };
            #[derive(Deserialize)]
            struct Row(HashMap<String, Value>);
            let Ok(rows) = serde_json::from_str::<Vec<Row>>(&b) else {
                return false;
            };
            let mut m: HashMap<String, bool> = HashMap::new();
            for r in rows {
                let Some(Value::String(v)) = r.0.get(field) else {
                    continue;
                };
                // "out" is already a repo path; "name" is a page stem
                if v.contains('/') {
                    m.insert(v.clone(), true);
                } else {
                    m.insert(format!("docs/demos/{}.html", v), true);
                }
            }
            guard.insert(manifest, m);
        }
        guard[manifest].get(p).copied().unwrap_or(false)
    }
}

fn find_repo_root_from(dir: &Path) -> Option<std::path::PathBuf> {
    // walk up from the cwd first; the tree may instead be located via
    // SHADLESS_ROOT or sit next to the crate — cargo test runs with the
    // crate as cwd. Root = the dir holding package.json with a pipeline/
    // directory (the engine lives at pipeline/ in the same repo).
    let is_root = |d: &Path| d.join("package.json").exists() && d.join("pipeline").is_dir();
    let mut d = dir.to_path_buf();
    loop {
        if is_root(&d) {
            return Some(d);
        }
        match d.parent() {
            Some(p) if p != d => d = p.to_path_buf(),
            _ => break,
        }
    }
    if let Ok(r) = std::env::var("SHADLESS_ROOT") {
        let p = std::path::PathBuf::from(r);
        if is_root(&p) {
            return Some(p);
        }
    }
    // test-only: resolve the real tree via the shared crate-adjacent
    // candidates (crate parent post-move, sibling checkout pre-move). Never
    // consulted in production (the cwd-walk and SHADLESS_ROOT win there).
    #[cfg(test)]
    {
        if let Some(alt) = crate::crate_adjacent_tree_root() {
            return Some(alt);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_audit_classify_order() {
        let cases: Vec<(&str, &str, &str)> = vec![
            // RTL variants must reach build-rtl, NOT the broader dist/components rule
            ("dist/components/alert-rtl-he.html", "programmatic", "pipeline/src/emit/build_rtl.rs"),
            ("dist/components/alert-rtl-en.html", "programmatic", "pipeline/src/emit/build_rtl.rs"),
            ("dist/components/alert-rtl-fa.html", "programmatic", "pipeline/src/emit/build_rtl.rs"),
            // alert-demo is the oracle's, carved out of the same rule
            ("dist/components/alert-demo.html", "programmatic", "pipeline/src/oracle/example_oracle.rs"),
            // a plain component page belongs to the emitter/demo rule
            ("dist/components/accordion.html", "programmatic",
             "./build/pipeline example-fixture (per-tier fixture)"),
            // docs/demos RTL variants are build-rtl output, not hand-authored —
            // programmatic patterns are consulted before hand-authored ones
            ("docs/demos/alert-rtl-he.html", "programmatic", "pipeline/src/emit/build_rtl.rs"),
            // a bare -rtl.html read as hand-authored too, and is not: the
            // oracle manifest claims it
            ("docs/demos/alert-rtl.html", "programmatic", "pipeline/src/oracle/example_oracle.rs"),
            // written by example-oracle from the React render, which its manifest records
            ("docs/demos/badge-demo.html", "programmatic", "pipeline/src/oracle/example_oracle.rs"),
            // IR json
            ("generated/ir/badge.json", "programmatic", "pipeline/src/convert/mod.rs"),
            // tool source
            ("pipeline/src/emit/demo.rs", "tool-source", ""),
            ("src/tags.mjs", "tool-source", ""),
            // pin.json is hand-authored even though it sits under src/registry
            ("src/registry/pin.json", "hand-authored",
             "pipeline upstream (re-pin) / human (vendor re-hash via ./build/pipeline pin --force)"),
            ("pipeline/src/main.rs", "tool-source", ""),
        ];
        for (path, kind, owner) in cases {
            let got = classify_path(path);
            assert_eq!(got.kind, kind, "{}: kind", path);
            if owner.is_empty() {
                continue;
            }
            assert_eq!(got.label(), owner, "{}: attributed", path);
        }
    }

    /// Go TestUnitAuditPatternsAreWellFormed: every pattern must set exactly
    /// one of tool/note/owner, and programmatic patterns carry a source.
    #[test]
    fn unit_audit_patterns_are_well_formed() {
        for (i, p) in programmatic_patterns().iter().enumerate() {
            assert!(!p.tool.is_empty(), "programmaticPatterns[{}] no label", i);
            assert!(
                !p.source.is_empty(),
                "programmaticPatterns[{}] ({}) no source",
                i,
                p.tool
            );
        }
        for (i, p) in tool_source_patterns().iter().enumerate() {
            assert!(!p.note.is_empty(), "toolSourcePatterns[{}] no label", i);
        }
        for (i, p) in hand_authored_patterns().iter().enumerate() {
            assert!(!p.owner.is_empty(), "handAuthoredPatterns[{}] no label", i);
        }
        for (i, h) in heuristic_hints().iter().enumerate() {
            assert!(!h.kind.is_empty(), "heuristicHints[{}] no kind", i);
            assert!(
                !h.tool.is_empty() || !h.note.is_empty() || !h.owner.is_empty(),
                "heuristicHints[{}] no suggestion payload",
                i
            );
        }
        for (i, p) in LLM_PATCH_POINTS.iter().enumerate() {
            assert!(
                !p.file.is_empty() && !p.what.is_empty(),
                "llmPatchPoints[{}] needs a file and an explanation",
                i
            );
        }
    }

    /// The specific heuristics must win over the dist/ catch-all.
    #[test]
    fn unit_audit_heuristic_order() {
        let cases = [
            ("dist/components/alert-rtl-he.html", "pipeline/src/emit/build_rtl.rs"),
            ("docs/demos/thing-demo.html", "pipeline/src/oracle/example_oracle.rs"),
            ("dist/glue/dialog-glue.js", "pipeline/src/emit/demo.rs"),
            // only the catch-all matches this one
            (
                "dist/widgets/new.html",
                "./build/pipeline example-fixture (per-tier fixture)",
            ),
        ];
        for (path, want_tool) in cases {
            let s = suggest_from_heuristics(path)
                .unwrap_or_else(|| panic!("{}: no heuristic matched", path));
            assert_eq!(s.tool, want_tool, "{}", path);
        }
    }

    #[test]
    fn unit_audit_walk_skips() {
        for rel in [
            ".git/config",
            "node_modules/x/index.js",
            ".upstream/shadcn-ui/a.tsx",
            "tools/contracts/out/dialog/oracle.html",
            "a/node_modules/b",
        ] {
            assert!(audit_should_skip(rel), "{} should be skipped", rel);
        }
        for rel in [
            "dist/components/accordion.html",
            "pipeline/src/emit/demo.rs",
            // the skip is a path prefix, not a substring: a sibling directory
            // whose name merely starts the same way must survive
            "tools/contracts/run.mjs",
            "tools/contracts/outer/x.mjs",
        ] {
            assert!(!audit_should_skip(rel), "{} should NOT be skipped", rel);
        }
    }

    #[test]
    fn unit_audit_walk_is_sorted_and_relative() {
        let root = std::env::temp_dir().join(format!(
            "shadless-audit-walk-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        for p in ["b/2.txt", "a/1.txt", "node_modules/x.txt", "c.txt"] {
            let full = root.join(p);
            std::fs::create_dir_all(full.parent().unwrap()).unwrap();
            std::fs::write(full, b"").unwrap();
        }
        let got = audit_walk(&root).unwrap();
        assert_eq!(got, vec!["a/1.txt", "b/2.txt", "c.txt"]);
    }

    /// Sibling suggestion must look at the SAME DIRECTORY only.
    #[test]
    fn unit_audit_suggest_from_siblings() {
        let all = vec![
            "dist/components/a.html".to_string(),
            "dist/components/b.html".to_string(),
            "dist/other/deep/x.html".to_string(),
            "dist/components/new.html".to_string(),
        ];
        let mut by_path: HashMap<String, Classification> = HashMap::new();
        for p in &all {
            by_path.insert(p.clone(), classify_path(p));
        }
        by_path.insert(
            "dist/components/new.html".to_string(),
            Classification {
                path: "dist/components/new.html".to_string(),
                kind: "unknown".to_string(),
                ..Classification::default()
            },
        );
        let s = suggest_from_siblings("dist/components/new.html", &all, &by_path)
            .expect("no sibling suggestion");
        assert_eq!(s.kind, "programmatic");
        assert_eq!(s.total, 2, "the deep one is in another directory");
        // a file with no classified siblings gets nothing rather than a guess
        assert!(
            suggest_from_siblings("lonely/x.txt", &["lonely/x.txt".to_string()], &by_path).is_none()
        );
    }

    #[test]
    fn unit_audit_parent_dir() {
        for (input, want) in [("a/b/c.txt", "a/b/"), ("c.txt", ""), ("a/c.txt", "a/")] {
            assert_eq!(parent_dir(input), want);
        }
    }

    /// Drift is "modified relative to HEAD". An untracked file is NOT drift —
    /// it is the normal state after `make build`.
    #[test]
    fn unit_audit_drift_ignores_untracked() {
        let root = std::env::temp_dir().join(format!(
            "shadless-audit-drift-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        std::fs::create_dir_all(&root).unwrap();
        let run = |args: &[&str]| -> bool {
            std::process::Command::new("git")
                .args(args)
                .current_dir(&root)
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        };
        if !run(&["init", "-q"])
            || !run(&["config", "user.email", "t@example.com"])
            || !run(&["config", "user.name", "t"])
        {
            eprintln!("skip: git unavailable");
            return;
        }
        std::fs::create_dir_all(root.join("dist")).unwrap();
        let tracked = root.join("dist/out.css");
        std::fs::write(&tracked, b"a{}").unwrap();
        assert!(run(&["add", "-A"]));
        assert!(run(&["commit", "-qm", "init"]));

        let programmatic = vec![
            Classification {
                path: "dist/out.css".to_string(),
                kind: "programmatic".to_string(),
                tool: "tailwind".to_string(),
                ..Classification::default()
            },
            Classification {
                path: "dist/globals.css".to_string(),
                kind: "programmatic".to_string(),
                tool: "tailwind".to_string(),
                ..Classification::default()
            },
        ];
        assert!(
            detect_drift(&root, &programmatic).is_empty(),
            "a clean tree reported drift"
        );
        // untracked: still not drift
        std::fs::write(root.join("dist/globals.css"), b"b{}").unwrap();
        assert!(
            detect_drift(&root, &programmatic).is_empty(),
            "an untracked build output was reported as drift"
        );
        // modified tracked file: that IS drift
        std::fs::write(&tracked, b"a{color:red}").unwrap();
        let d = detect_drift(&root, &programmatic);
        assert_eq!(d.len(), 1);
        assert_eq!(d[0].path, "dist/out.css");
    }
}
