#!/usr/bin/env node
// example-oracle: upstream examples/*.tsx → shadless demo HTML, 1:1 by
// construction.
//
// Architecture (render every upstream docs example as a test case,
// comparing 1:1 restoration):
//
//   1. BUILD: for each examples/radix/<name>.tsx, esbuild-bundle the REAL
//      React + registry sources from the pinned checkout, render in a real
//      browser (chromium), extract #root.innerHTML → that DOM *is* the
//      demo page body. No hand-authoring, no hand-copied classes — the
//      rendered oracle carries data-slots, aria attrs, cn-* classes and
//      lucide svg bodies exactly as ui.shadcn.com renders them.
//   2. GATE (--check): re-render the oracle and byte-diff the normalized
//      DOM against the emitted page — catches pipeline tampering, upstream
//      evolution past the pin, and emitter regressions. Computed styles
//      need no separate oracle page: same DOM + same out.css on both
//      sides; DOM equality IS the golden master.
//
// Replaces the docs/demos hand-authored layer (301 files — alert-colors
// hardcoded-hex drift was born there) and the build-demo.mjs hand emitter
// (alert-demo's inline styles were invalid dead code: hsl(var(--border))
// against oklch tokens).
//
// Normalization (both sides, extraction + check): radix auto-ids
// (radix-:rN: / radix-_r_N) and --radix-* style vars are runtime noise,
// not contract. Static initial renders otherwise need nothing.
//
// Scope guard: kernel-tier -demo pages (dialog, select, …) keep their
// fixture+glue path — their behavior is contracts' domain; this tool
// never touches them.
import { chromium } from "playwright"
import { readdirSync, readFileSync, writeFileSync, existsSync, rmSync } from "node:fs"
import { resolve } from "node:path"
import { injectPrePaint } from "../src/docs/theme-prepaint.mjs"
import { buildOracle, awaitOracle, norm } from "./oracle-lib.mjs"

const EXAMPLES = ".upstream/shadcn-ui/apps/v4/examples/radix"
const CATALOG = "docs/catalog.json"
const CHECK = process.argv.includes("--check")

// Target set: every authored demo whose upstream example exists
// (docs/catalog.json status=authored, docs/demos/<name>.html) plus
// alert-demo (replacing the retired build-demo hand emitter). Dynamic —
// new upstream examples flow in with zero tool edits. mode-toggle is a
// shadless-own guide demo (no upstream file) and stays hand-authored.
// Ownership is recorded in docs/example-oracle.json; --check only gates
// owned pages. A render failure is FATAL: the run writes nothing (pages
// or manifests) and exits 1. It used to be survivable — a failed render
// printed KEEP and the manifest was rewritten to whatever *did* render,
// so a broken run silently shrank the owned set (once to zero pages) and
// every downstream gate that reads the manifest went green over an empty
// surface.
const MANIFEST = "docs/example-oracle.json"
function loadTargets() {
  const catalog = JSON.parse(readFileSync("docs/catalog.json", "utf8"))
  // Kernel-tier -demo previews keep the existing fixture path
  // (dist/components/<name>.html with <template> + radix-kernel glue):
  // oracle's static DOM has no Portal target, so opening-popup kernel
  // demos (dialog, select, popover, …) fail to open. The kernel
  // fixture's <template id="d1-portal"> is the mount target — it MUST
  // exist for the runtime to materialize dialog content. A -demo is
  // kernel iff its underlying component (the name without "-demo") is
  // tier=kernel in tiers.json.
  const tiers = JSON.parse(readFileSync("src/registry/tiers.json", "utf8"))
  const isKernelDemo = (demoName) => {
    const m = /^(.+)-demo$/.exec(demoName); if (!m) return false
    return tiers[m[1]]?.tier === "kernel"
  }
  // alert-demo replaces the retired build-demo hand emitter (dist target
  // + padding:1rem body — the docs host page historically framed it that
  // way; every other oracle page uses the standard p-8).
  const targets = [{ name: "alert-demo", out: "dist/components/alert-demo.html", bodyStyle: "padding:1rem" }]
  const skipped = []
  for (const p of catalog.previews) {
    if (!existsSync(`${EXAMPLES}/${p.name}.tsx`)) { skipped.push(p.name); continue }
    if (p.status !== "authored" && p.status !== "existing-dist") continue
    if (p.name === "alert-demo") continue // already in targets above
    if (isKernelDemo(p.name)) { skipped.push(p.name); continue } // keep dist fixture
    // dialog-family examples are INTERACTIVE fixtures generated by
    // tools/example-fixture.mjs (oracle renders are static snapshots —
    // dead buttons); the fixture tool owns their docs/demos pages
    targets.push({ name: p.name, out: `docs/demos/${p.name}.html` })
  }
  return { targets: targets.filter((t, i, a) => a.findIndex((x) => x.name === t.name) === i), skipped }
}

// Trivial-tier families (accordion, checkbox, collapsible, switch, toggle,
// radio-group, …) become INTERACTIVE by loading the runtime: shadless.js
// wires by data-slot and the oracle's closed-state DOM is the React shape
// the runtime is contract-tested against. The scripts live in <head>
// (deferred) so the <body> stays byte-equal to the oracle render — that is
// what --check and the golden hop compare. Kernel families need their glue
// protocol (tools/example-fixture.mjs); static families need nothing.
const TIERS_ALL = JSON.parse(readFileSync("src/registry/tiers.json", "utf8"))
// by CONTENT: a field example with a checkbox in it needs the runtime as
// much as checkbox-basic does
// which trivial-js components have a behavior file (dist/js/<c>.js)
const TRIVIAL_JS = readdirSync("src/runtime/components").map((f) => f.slice(0, -3)).filter((c) => TIERS_ALL[c]?.tier === "trivial-js")
const TRIVIAL_SEL = Object.fromEntries(TRIVIAL_JS.map((c) => [c, `[data-slot="${c}"]`]))
// base + one file per component present, deferred (auto-init on DOMContentLoaded)
const scriptsHead = (trivial) => trivial.length
  ? `\n<script defer src="../shadless.js"></script>` + trivial.map((c) => `\n<script defer src="../js/${c}.js"></script>`).join("") : ""
const pageHtml = (name, body, bodyAttr, trivial) => `<!doctype html>
<html><head><meta charset="utf-8"><title>shadless ${name}</title>
<link rel="stylesheet" href="../out.css">${injectPrePaint("")}${scriptsHead(trivial)}</head>
<body ${bodyAttr ?? 'class="p-8"'}>
${body}
</body></html>`

const browser = await chromium.launch()
const page = await browser.newPage()
const { targets: TARGETS, skipped } = loadTargets()
if (skipped.length) console.log(`oracle: ${skipped.length} authored demos have no upstream example (kept hand-authored): ${skipped.join(", ")}`)

if (CHECK) {
  const owned = JSON.parse(readFileSync(MANIFEST, "utf8"))
  let drift = 0
  for (const t of owned) {
    try {
      const { htmlFile } = await buildOracle(t.name)
      await awaitOracle(page, htmlFile)
      const dom = norm(await page.evaluate(() => document.querySelector("#root").innerHTML))
      rmSync(htmlFile)
      const current = readFileSync(t.out, "utf8")
      const body = /<body[^>]*>\n([\s\S]*)\n<\/body>/.exec(current)?.[1] ?? ""
      if (norm(body.trim()) !== dom.trim()) {
        console.error(`DRIFT [${t.name}]: ${t.out} != oracle render`)
        drift++
      }
    } catch (err) {
      console.error(`DRIFT [${t.name}]: oracle render failed (${err.message.split("\n")[0]})`)
      drift++
    }
  }
  await browser.close()
  if (drift) { console.error(`FAIL  example-oracle check (${drift}/${owned.length} drifted)`); process.exit(1) }
  console.log(`PASS  example-oracle check (${owned.length} pages == oracle render)`)
  process.exit(0)
}

// Ownership by CONTENT, not by name: a page whose rendered DOM contains a
// kernel-family root or trigger (a dropdown inside an avatar example, a
// tooltip inside a button example) is handed to tools/example-fixture.mjs,
// which knows those families' protocols; its target list is this manifest.
// The oracle still renders such pages (the fixture tool re-renders them
// itself) but does not write or own them.
const FIXTURE_FAMILIES = {
  "alert-dialog": '[data-slot="alert-dialog-trigger"]', "dialog": '[data-slot="dialog-trigger"]', "sheet": '[data-slot="sheet-trigger"]',
  "popover": '[data-slot="popover-trigger"]', "tooltip": '[data-slot="tooltip-trigger"]', "hover-card": '[data-slot="hover-card-trigger"]',
  "dropdown-menu": '[data-slot="dropdown-menu-trigger"]', "context-menu": '[data-slot="context-menu-trigger"]', "menubar": '[data-slot="menubar"]',
  "select": '[data-slot="select-trigger"]', "tabs": '[data-slot="tabs"]', "slider": '[data-slot="slider"]', "scroll-area": '[data-slot="scroll-area"]',
  "carousel": '[data-slot="carousel"]', "navigation-menu": '[data-slot="navigation-menu"]',
}
const FIXTURE_TARGETS = "docs/example-fixture-targets.json"
const fixtureTargets = []
const rendered = []
const failures = []
// Phase 1 — render everything, write nothing. The run is ALL-OR-NOTHING:
// a partial emit leaves the tree half-generated and, worse, rewrites the
// two manifests to describe only the pages that happened to survive, which
// is indistinguishable downstream from "those pages were never ours".
for (const t of TARGETS) {
  const tsx = `${EXAMPLES}/${t.name}.tsx`
  if (!existsSync(tsx)) { failures.push(`${t.name}: ${tsx} missing`); continue }
  try {
    const { htmlFile } = await buildOracle(t.name)
    await awaitOracle(page, htmlFile)
    const dom = norm(await page.evaluate(() => document.querySelector("#root").innerHTML))
    const families = await page.evaluate((fams) => Object.entries(fams).filter(([, sel]) => document.querySelector("#root " + sel)).map(([f]) => f), FIXTURE_FAMILIES)
    const trivial = await page.evaluate((sels) => Object.entries(sels).filter(([, sel]) => document.querySelector("#root " + sel)).map(([c]) => c), TRIVIAL_SEL)
    rmSync(htmlFile)
    if (families.length && t.out.startsWith("docs/demos/")) { fixtureTargets.push({ name: t.name, families, trivial }); continue }
    rendered.push({ t, dom: dom.trim(), trivial })
  } catch (err) {
    failures.push(`${t.name}: oracle render failed (${err.message.split("\n")[0]})`)
  }
}
await browser.close()

if (failures.length) {
  for (const f of failures) console.error(`FAIL [${f.split(":")[0]}]: ${f.slice(f.indexOf(":") + 2)}`)
  console.error(`FAIL  example-oracle (${failures.length}/${TARGETS.length} examples did not render) — ` +
    `nothing written; ${MANIFEST} and ${FIXTURE_TARGETS} keep their previous contents`)
  process.exit(1)
}

// Phase 2 — every target rendered; commit pages and manifests together.
for (const { t, dom, trivial } of rendered) {
  const attr = t.bodyStyle ? `style="${t.bodyStyle}"` : undefined
  writeFileSync(t.out, pageHtml(t.name, dom, attr, trivial))
}
writeFileSync(MANIFEST, JSON.stringify(rendered.map(({ t }) => ({ name: t.name, out: t.out })), null, 1) + "\n")
writeFileSync(FIXTURE_TARGETS, JSON.stringify(fixtureTargets.sort((a, b) => a.name.localeCompare(b.name)), null, 1) + "\n")
console.log(`example-oracle: ${fixtureTargets.length} pages carry kernel families — handed to tools/example-fixture.mjs (${FIXTURE_TARGETS})`)
console.log(`example-oracle: ${rendered.length} pages emitted from React oracle (${TARGETS.length} targets, 0 failures)`)
