// example-static.mjs — build a static example page from the IR.
//
// The 105 example pages that need JS are generated by tools/example-fixture.mjs,
// which exists to WIRE kernel families (portal ids, controlled-open state, the
// FAMILY protocol table). A page with no family has nothing to wire, so that
// tool skips it — `if (!target.families.length) continue` — and the remaining
// ~200 pages have been hand-authored instead. They do not need wiring; they
// need assembly, which is a different job and this file.
//
// The rules are three, and the IR already carries what each one needs:
//
//   native tag        <div className=…>  ->  <div class=…>, verbatim
//   component usage   <Badge variant=x>  ->  the component's IR element, with
//                     its cva base plus the classes for that variant, and
//                     data-slot / data-variant recording which
//   children          recurse
//
// This is what src/converter/index.mjs already does for a component's own
// DEFINITION, applied to component USAGES instead. It is deliberately not part
// of the converter: the converter's output is the IR, and this consumes it.
//
// Verification is free. tools/example-oracle.mjs renders the same upstream
// example with real React, and the example-gate asserts every shipped page
// equals a fresh oracle render — so a page this produces is judged by the
// same oracle as a hand-authored one.
//
//   node tools/example-static.mjs <name>            print to stdout
//   node tools/example-static.mjs <name> --write    write docs/demos/<name>.html

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs"
import { parse } from "@babel/parser"
import { twMerge } from "tailwind-merge"

const EXAMPLES = ".upstream/shadcn-ui/apps/v4/examples/radix"
const IRDIR = "src/registry/ir"

const name = process.argv[2]
const write = process.argv.includes("--write")
if (!name) {
  console.error("usage: node tools/example-static.mjs <name> [--write]")
  process.exit(2)
}

const irCache = new Map()
function loadIr(component) {
  if (irCache.has(component)) return irCache.get(component)
  const p = `${IRDIR}/${component}.json`
  const ir = existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : null
  irCache.set(component, ir)
  return ir
}

// A component name in an example (<Badge>) maps to the IR that exports that
// function. Scanning every IR is cheap and avoids a second naming table that
// could disagree with the converter's.
const exportIndex = new Map()
function indexExports() {
  if (exportIndex.size) return exportIndex
  for (const f of readdirSync(IRDIR).filter((x) => x.endsWith(".json"))) {
    const ir = JSON.parse(readFileSync(`${IRDIR}/${f}`, "utf8"))
    for (const c of ir.components) if (c.export) exportIndex.set(c.fn, ir)
  }
  return exportIndex
}

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")

// cva resolution: base classes plus the classes for each chosen variant,
// falling back to the table's declared defaults — the same model the emitter
// uses for the attribute API.
function cvaClasses(ir, fn, props) {
  const table = Object.values(ir.cva)[0]
  if (!table) return { classes: "", variantAttrs: {} }
  const parts = [table.base]
  const variantAttrs = {}
  for (const [axis, choices] of Object.entries(table.variants ?? {})) {
    const chosen = props[axis] ?? table.defaults?.[axis]
    if (chosen == null) continue
    variantAttrs[`data-${axis}`] = String(chosen)
    if (choices[chosen]) parts.push(choices[chosen])
  }
  // twMerge, not concatenation. cva composes base + variant and React resolves
  // the conflicts through tailwind-merge, so a variant that sets
  // focus-visible:ring-destructive/20 REMOVES the base's ring-ring/50 rather
  // than sitting after it. Concatenating leaves both, which renders the same
  // in a browser but does not match the oracle byte for byte — and the
  // committed pages carry the merged form.
  return { classes: twMerge(parts.filter(Boolean).join(" ")), variantAttrs }
}

function attrText(node) {
  const out = {}
  for (const a of node.attributes ?? []) {
    if (a.type !== "JSXAttribute") continue
    const key = a.name.name
    if (a.value == null) { out[key] = true; continue }
    if (a.value.type === "StringLiteral") out[key] = a.value.value
    else if (a.value.type === "JSXExpressionContainer" &&
             a.value.expression.type === "StringLiteral") out[key] = a.value.expression.value
    else out[key] = { unsupported: a.value.type }
  }
  return out
}

function renderChildren(children) {
  return children.map(renderNode).filter(Boolean).join("")
}

function renderNode(node) {
  if (node.type === "JSXText") {
    const t = node.value.replace(/\s+/g, " ")
    return t.trim() ? esc(t.trim()) : ""
  }
  if (node.type !== "JSXElement") {
    throw new Error(`unsupported node ${node.type} — this example needs more than assembly`)
  }
  const el = node.openingElement
  const tagName = el.name.name
  const props = attrText(el)
  const kids = renderChildren(node.children)

  // a lowercase tag is a real element: pass it through
  if (/^[a-z]/.test(tagName)) {
    const attrs = Object.entries(props).map(([k, v]) => {
      const key = k === "className" ? "class" : k
      if (v === true) return ` ${key}`
      if (typeof v === "object") throw new Error(`${tagName}.${k}: ${v.unsupported}`)
      return ` ${key}="${esc(v)}"`
    }).join("")
    const VOID = new Set(["br", "hr", "img", "input", "meta", "link"])
    return VOID.has(tagName) ? `<${tagName}${attrs}>` : `<${tagName}${attrs}>${kids}</${tagName}>`
  }

  // a capitalised tag is a component usage: resolve through its IR
  const ir = indexExports().get(tagName)
  if (!ir) throw new Error(`no IR exports ${tagName}`)
  const comp = ir.components.find((c) => c.fn === tagName)
  const root = comp.elements[0]
  if (!root) throw new Error(`${tagName}: IR has no elements`)

  const tag = ir.tagHints?.[root.tag] ?? (/^[a-z]/.test(root.tag) ? root.tag : "div")
  const { classes, variantAttrs } = cvaClasses(ir, tagName, props)
  const attrs = { "data-slot": root.slot, ...variantAttrs }
  const extra = Object.entries(props)
    .filter(([k]) => !(k in (Object.values(ir.cva)[0]?.variants ?? {})))
    .filter(([k]) => k !== "className" && k !== "children")
  for (const [k, v] of extra) attrs[k] = v

  const attrStr = Object.entries(attrs)
    .map(([k, v]) => (v === true ? ` ${k}` : ` ${k}="${esc(v)}"`)).join("")
  const cls = [classes, props.className].filter(Boolean).join(" ")
  return `<${tag}${attrStr}${cls ? ` class="${esc(cls)}"` : ""}>${kids}</${tag}>`
}

// ---- drive -----------------------------------------------------------------

const src = readFileSync(`${EXAMPLES}/${name}.tsx`, "utf8")
const ast = parse(src, { sourceType: "module", plugins: ["typescript", "jsx"] })

// Upstream uses both `export default function X()` and `export function X()`
// — roughly 100 of the static examples use the named form, so keying on the
// default export alone found nothing in most of them.
let root = null
for (const node of ast.program.body) {
  let fn = null
  if (node.type === "ExportDefaultDeclaration") fn = node.declaration
  else if (node.type === "ExportNamedDeclaration" &&
           node.declaration?.type === "FunctionDeclaration") fn = node.declaration
  if (!fn) continue
  const ret = (fn.body?.body ?? []).find((s) => s.type === "ReturnStatement")
  if (ret?.argument) { root = ret.argument; break }
}
if (!root) throw new Error(`${name}: no exported function with a JSX return`)
if (root.type === "JSXFragment") throw new Error(`${name}: fragment root not handled yet`)

const body = renderNode(root)
const PREPAINT = readFileSync("src/docs/theme-prepaint.mjs", "utf8")
  .match(/export const THEME_PREPAINT_SCRIPT = `([^`]*)`/)[1]

const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>shadless ${name}</title>
<link rel="stylesheet" href="../out.css">${PREPAINT}</head>
<body class="p-8">
${body}
</body></html>`

if (write) {
  writeFileSync(`docs/demos/${name}.html`, html)
  console.log(`wrote docs/demos/${name}.html`)
} else {
  process.stdout.write(html)
}
