//! Port of pipeline/nodes.go — THE pipeline graph, single source of truth.
//! Transcribed field-for-field: any drift shows up as a key mismatch in the
//! `status` golden-diff against the Go binary. `inputs: None` is Go's nil
//! (never fresh); `produces: None` is Go's nil (no declared outputs).

// Two pinned-upstream trees that several nodes read DIRECTLY (nodes.go:
// declared whole rather than per-file; over-declaring an input only costs a
// rerun).
const UPSTREAM_EXAMPLES_GLOB: &str = ".upstream/shadcn-ui/apps/v4/examples/**";
const UPSTREAM_DOCS_GLOB: &str = ".upstream/shadcn-ui/apps/v4/content/docs/**";

// docsUpstreamMirror: the tracked, git-diffable copy of the upstream docs .mdx.
const DOCS_UPSTREAM_MIRROR: &str = "generated/docs-upstream";

#[derive(Clone, Debug)]
pub struct Node {
    pub id: String,
    pub kind: String, // "build" (produces artifacts) | "gate" (asserts, produces nothing)
    pub tier: String, // "fast" | "full"
    pub needs: Vec<String>,
    pub run: Vec<Vec<String>>,
    pub inputs: Option<Vec<String>>, // None = judges state outside the tree, never fresh
    pub produces: Option<Vec<String>>,
    pub why: String,
    pub mutations: Vec<String>,
}

impl Node {
    pub fn never_fresh(&self) -> bool {
        self.inputs.is_none()
    }
}

#[allow(clippy::too_many_arguments)]
fn node(
    id: &str,
    kind: &str,
    tier: &str,
    needs: &[&str],
    run: &[&[&str]],
    inputs: Option<&[&str]>,
    produces: Option<&[&str]>,
    why: &str,
    mutations: &[&str],
) -> Node {
    Node {
        id: id.to_string(),
        kind: kind.to_string(),
        tier: tier.to_string(),
        needs: needs.iter().map(|s| s.to_string()).collect(),
        run: run
            .iter()
            .map(|c| c.iter().map(|s| s.to_string()).collect())
            .collect(),
        inputs: inputs.map(|v| v.iter().map(|s| s.to_string()).collect()),
        produces: produces.map(|v| v.iter().map(|s| s.to_string()).collect()),
        why: why.to_string(),
        mutations: mutations.iter().map(|s| s.to_string()).collect(),
    }
}

/// The pipeline graph, in declaration order (nodes.go `var Nodes`).
pub fn all() -> Vec<Node> {
    vec![
        node(
            "pin", "gate", "fast",
            &[],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestPin$", "."]],
            Some(&["pipeline/gate_pin.go", "pipeline/gates_test.go", "src/registry/pin.json", "vendor/**", ".upstream/shadcn-ui/.git/HEAD"]),
            None,
            "the .upstream checkout must sit exactly at the pinned release tag; upgrade tools write pin.json directly and nothing else checks the result",
            &["pin-commit-drift", "pin-base-drift"],
        ),
        node(
            "unit", "gate", "fast",
            &["build-js"],
            &[&["node", "tools/unit-check.mjs"], &["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestUnit", "./..."]],
            Some(&[
                "tools/unit-check.mjs", "tools/unit/**", "src/**", "generated/ir/**", "tools/**/*.mjs",
                "vendor/**", "package.json", "dist/esm/**", "dist/shadless.js", "probes/h4/globals.css",
                ".upstream/shadcn-ui/apps/v4/registry/styles/style-nova.css", "pipeline/*.go",
                "pipeline/internal/**", "docs/example-oracle.json", "docs/example-fixture-targets.json",
            ]),
            None,
            "seconds-level guard over the pure functions cleanup rounds touch; born from a dead-code delete in rewritePaths that only surfaced minutes later",
            &["unit-break-pure-fn"],
        ),
        node(
            "typecheck", "gate", "fast",
            &[],
            &[&["npx", "tsc", "-p", "tsconfig.json"]],
            Some(&["src/**", "tsconfig.json", "package.json", "package-lock.json"]),
            None,
            "the JSDoc types are the IR/emit contract — checkJs keeps them machine-checked; npm run verify alone would not enforce it for direct pipeline runs",
            &["typecheck-break-ir-contract"],
        ),
        node(
            "ledger", "gate", "fast",
            &[],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestLedger$", "."]],
            Some(&[
                "pipeline/ledger.go", "pipeline/jssource.go", "pipeline/interactivity_sweep.go",
                "pipeline/gates_test.go", "gates/ledger.json", "gates/*-baseline.json",
                "src/registry/pin.json", "src/registry/upstream-snapshot/exemptions.json",
                "tools/contracts/components/**", "src/**",
            ]),
            None,
            "every recorded exemption must be schema-valid, still present in its source, and inside its budget — scattered flags rot silently",
            &["ledger-undocumented-exemption", "ledger-budget-exceeded"],
        ),
        node(
            "script-refs", "gate", "fast",
            &[],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestScriptRefs$", "."]],
            Some(&["pipeline/gate_script_refs.go", "pipeline/gates_test.go", "pipeline/main.go", "pipeline/*_test.go", "package.json", "Makefile"]),
            None,
            "a node/pipeline call in Makefile or package.json scripts must resolve to a real file, a real pipeline subcommand, or a real go test — the Go port deleted gates/overlay.mjs, gates/path-parity.mjs, tools/example-oracle.mjs, tools/example-fixture.mjs and tools/css-direction-gate.mjs while three Makefile targets and four npm scripts kept calling them, silent until run",
            &["script-refs-dead-node-call"],
        ),
        node(
            "dist-complete", "gate", "fast",
            &["demo-css", "product-css"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestDistComplete$", "."]],
            Some(&["pipeline/gate_dist_complete.go", "pipeline/gates_test.go", "dist/css/**", "dist/out.css"]),
            None,
            "the tracked no-build dist/out.css must carry every slot selector its per-component sources declare — a partial-build out.css (static pages only) got committed once and no gate asked whether the file was whole",
            &["dist-complete-drop-component"],
        ),
        node(
            "pack", "gate", "fast",
            &["build-js", "product-build"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestPack$", "."]],
            Some(&["pipeline/gate_pack.go", "pipeline/gates_test.go", "package.json", "README.md", "dist/**"]),
            None,
            "the npm surface — exports map, tarball contents, README specifiers, an empty dependencies — must agree: a bare-string ./runtime.min export served an IIFE to `import`, README documented a specifier that does not resolve, and a React-free package installed React through dependencies",
            &["pack-broken-export"],
        ),
        node(
            "coverage", "gate", "fast",
            &["convert", "example-oracle"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestCoverage$", "."]],
            Some(&[
                "pipeline/gate_coverage.go", "pipeline/gate_coverage_budget.go", "pipeline/gates_test.go",
                "gates/ledger.json", "src/registry/tiers.json", "generated/ir/**", "docs/example-oracle.json",
                "docs/demos/**", "tools/contracts/components/**",
            ]),
            Some(&["build/gates/coverage.json"]),
            "the product surface (component x path x theme x dir x state) as a matrix with the gate covering each cell; the UNCOVERED count is budgeted and may only shrink — every historical bug sat in a cell no gate had been written for",
            &["coverage-drop-contract"],
        ),
        node(
            "overlay", "gate", "fast",
            &["convert", "example-oracle"],
            &[&["./build/pipeline", "overlay", "--audit"]],
            Some(&[
                "pipeline/overlay.go", "pipeline/default_content.go", "pipeline/docs_transforms.go",
                "pipeline/emitter_css.go", "pipeline/resolve_skins.go", "pipeline/jssource.go",
                "pipeline/browser_shell.go", "pipeline/build_rtl.go", "pipeline/main.go",
                "tools/browser-shell.mjs", "tools/contracts/components/**", "src/emitter/skin.mjs",
                "src/registry/rtl-translations.json", "generated/ir/**", "src/registry/pin.json",
                "src/runtime/components/**", "src/runtime/core.js", "overlays/**", "docs/example-oracle.json",
                "docs/example-fixture-targets.json", "docs/demos/**",
                UPSTREAM_EXAMPLES_GLOB, UPSTREAM_DOCS_GLOB,
            ]),
            None,
            "every manual intervention on top of the mechanical conversion (rule tables, hand-written fixtures/glue/runtime, upstream patches) must still apply to the pinned upstream — orphaned rules and stale authored files fail here, with task packets, instead of silently no-op'ing like the old find/replace overlay",
            &["overlay-stale-authored", "overlay-orphaned-rule"],
        ),
        node(
            "convert", "build", "full",
            &["pin", "build-js"],
            &[&["./build/pipeline", "resolve-skins"], &["./build/pipeline", "convert"]],
            Some(&[
                "pipeline/convert.go", "pipeline/resolve_skins.go", "pipeline/internal/twmerge/**",
                "pipeline/internal/tsx/**", "src/registry/tiers.json", "src/registry/pin.json",
                "src/kernel/**", ".upstream/shadcn-ui/apps/v4/registry/bases/radix/**",
                ".upstream/shadcn-ui/apps/v4/registry/styles/style-nova.css",
            ]),
            Some(&["generated/ir", "build/resolved-ui"]),
            "registry .tsx -> IR JSON, with its own drift gate against the pinned source",
            &[],
        ),
        node(
            "emit", "build", "full",
            &["convert", "build-js"],
            &[&["./build/pipeline", "emit"]],
            Some(&[
                "pipeline/emit.go", "pipeline/emitter_css.go", "pipeline/emitter_html.go",
                "pipeline/default_content.go", "pipeline/prepaint.go", "pipeline/tags.go",
                "pipeline/resolve_skins.go", "src/registry/tiers.json", "generated/ir/**",
                "probes/h4/globals.css",
            ]),
            Some(&["dist/components/*.html", "!dist/components/*-rtl-*.html", "dist/shadless.css", "build/emit"]),
            "static-tier emit: IR -> component html + per-slot css",
            &[],
        ),
        node(
            "build-js", "build", "fast",
            &[],
            &[&["./build/pipeline", "build-js"]],
            Some(&["pipeline/jsbuild.go", "src/runtime/**", "vendor/**"]),
            Some(&["dist/shadless.js", "dist/js", "dist/shadless.min.js", "dist/esm"]),
            "the JS surface: dist/shadless.js (kernel + base) and dist/js/<name>.js per component",
            &[],
        ),
        node(
            "contract-fixture", "build", "full",
            &["convert", "build-js"],
            &[&["./build/pipeline", "example-fixture", "--contracts"]],
            Some(&[
                "pipeline/example_fixture.go", "pipeline/ef_harvest_layer.js", "pipeline/ef_menu_ids.js",
                "pipeline/ef_nav_ids.js", "pipeline/ef_tabs.js", "pipeline/ef_api.js",
                "pipeline/oracle_lib.go", "pipeline/browser_shell.go", "tools/browser-shell.mjs",
                "pipeline/prepaint.go", "pipeline/docs_families.go", "pipeline/resolve_skins.go",
                "src/emitter/skin.mjs", "tools/contracts/components/**", "tools/contracts/stubs/**",
                "src/registry/pin.json", "package-lock.json", "dist/out.css",
            ]),
            Some(&["src/kernel/*.html"]),
            "the kernel contract fixtures (src/kernel/*.html) are harvested from the contract defs' own React render — hand-mirrored fixtures drifted in content and classes (the bulk of style-parity's recorded cells)",
            &[],
        ),
        node(
            "example-oracle", "build", "full",
            &["emit", "build-js"],
            &[&["./build/pipeline", "example-oracle"]],
            Some(&[
                "pipeline/example_oracle.go", "pipeline/oracle_lib.go", "pipeline/resolve_skins.go",
                "pipeline/oracle_canon.js", "pipeline/browser_shell.go", "tools/browser-shell.mjs",
                "pipeline/prepaint.go", "src/registry/tiers.json", "src/runtime/components/**",
                "docs/catalog.json", "tools/contracts/stubs/**", "src/emitter/skin.mjs",
                "src/registry/pin.json", "src/registry/upstream-snapshot/exemptions.json",
                "package-lock.json", UPSTREAM_EXAMPLES_GLOB,
            ]),
            Some(&[
                "docs/demos/*.html", "!docs/demos/*-rtl-*.html", "docs/example-oracle.json",
                "docs/example-fixture-targets.json", "dist/components/alert-demo.html",
            ]),
            "upstream examples rendered by real React+chromium BECOME the demo pages — 1:1 with upstream by construction, not by hand-mirroring",
            &["example-oracle-render-failure"],
        ),
        node(
            "example-fixture", "build", "full",
            &["example-oracle"],
            &[&["./build/pipeline", "example-fixture"]],
            Some(&[
                "pipeline/example_fixture.go", "pipeline/ef_harvest_layer.js", "pipeline/ef_menu_ids.js",
                "pipeline/ef_nav_ids.js", "pipeline/ef_tabs.js", "pipeline/ef_api.js",
                "pipeline/oracle_lib.go", "pipeline/browser_shell.go", "tools/browser-shell.mjs",
                "pipeline/prepaint.go", "pipeline/docs_families.go", "pipeline/resolve_skins.go",
                "src/emitter/skin.mjs", "docs/example-fixture-targets.json", "dist/js/**",
                "tools/contracts/stubs/**", "src/registry/pin.json", "package-lock.json",
                "dist/out.css", UPSTREAM_EXAMPLES_GLOB,
            ]),
            Some(&["docs/demos/*.html", "!docs/demos/*-rtl-*.html"]),
            "kernel-tier examples as INTERACTIVE fixtures harvested from the oracle; the oracle alone emits static snapshots with dead buttons",
            &[],
        ),
        node(
            "rtl-dict", "build", "fast",
            &["pin", "build-js"],
            &[&["./build/pipeline", "rtl-dict"]],
            Some(&["pipeline/rtl_dict.go", "src/registry/tiers.json", ".upstream/shadcn-ui/apps/v4/examples/aria/**"]),
            Some(&["src/registry/rtl-translations.json"]),
            "the RTL translation dictionaries, lifted out of upstream's aria registry into a file this repo owns — so exactly one declared edge reaches a registry we do not build from, and `reproducible` catches it drifting",
            &["rtl-dict-missing-dictionary"],
        ),
        node(
            "demo-rtl", "build", "full",
            &["example-oracle", "example-fixture", "rtl-dict", "build-js"],
            &[&["./build/pipeline", "build-rtl"]],
            Some(&["pipeline/build_rtl.go", "pipeline/rtl_dict.go", "src/registry/tiers.json"]),
            Some(&["dist/components/*-rtl-*.html", "docs/demos/*-rtl-*.html", "build/rtl-langs.json"]),
            "AR/HE/EN/FA variants derived from the Arabic oracle page + upstream dictionaries",
            &[],
        ),
        node(
            "demo", "build", "full",
            &["demo-rtl", "example-fixture", "contract-fixture", "build-js"],
            &[&["./build/pipeline", "demo"]],
            Some(&[
                "pipeline/demo.go", "pipeline/emitter_css.go", "pipeline/default_content.go",
                "pipeline/prepaint.go", "pipeline/tags.go", "pipeline/resolve_skins.go",
                "src/registry/tiers.json", "generated/ir/**", "src/kernel/**", "probes/h4/globals.css",
                "probes/t7/**", "probes/t8/**",
            ]),
            Some(&[
                "dist/globals.css", "dist/demo-index.html", "dist/css",
                "dist/components/*.html", "!dist/components/*-rtl-*.html",
            ]),
            "unified globals.css (slot rules folded in) + the demo index + the per-component @apply sources the npm surface exports",
            &[],
        ),
        node(
            "product-css", "build", "full",
            &["demo"],
            &[&["./build/pipeline", "product-css"]],
            Some(&["pipeline/product_css.go", "pipeline/main.go", "src/docs/theme-prepaint.mjs", "probes/h4/globals.css", "package-lock.json"]),
            Some(&["dist/shadless-core.css", "dist/shadless.product.css"]),
            "token extraction + the product entry — the consumer-facing surface",
            &[],
        ),
        node(
            "demo-css", "build", "full",
            &["demo"],
            &[&["./build/pipeline", "tw", "dist/globals.css", "dist/out.css", "--cwd", "."]],
            Some(&[
                "pipeline/tw.go", "pipeline/main.go", "dist/globals.css", "dist/components/**",
                "dist/js/**", "docs/demos/**", "docs/content/**", "src/kernel/**",
                "tools/contracts/out/**", "generated/ir/**", "probes/t7/**", "probes/t8/**", "package.json",
            ]),
            Some(&["dist/out.css"]),
            "the stylesheet every demo page and contract fixture actually loads",
            &[],
        ),
        node(
            "product-build", "build", "full",
            &["product-css"],
            &[
                &["./build/pipeline", "tw", "dist/shadless.product.css", "dist/shadless.full.css"],
                &["./build/pipeline", "tw", "dist/shadless.product.css", "dist/shadless.full.min.css", "--minify"],
            ],
            Some(&["pipeline/tw.go", "pipeline/main.go", "dist/shadless.product.css", "package.json"]),
            Some(&["dist/shadless.full.css", "dist/shadless.full.min.css"]),
            "the no-build distribution artifact",
            &[],
        ),
        node(
            "product-verify", "gate", "full",
            &["product-build", "demo-css"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestProductVerify$", "."]],
            Some(&["pipeline/product_css.go", "pipeline/gates_test.go", "dist/**"]),
            None,
            "slot rules survive the product compile and docs chrome stays out of it",
            &["product-drop-slot-rule"],
        ),
        node(
            "consumer-sim", "gate", "full",
            &["product-css"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestConsumerSim$", "."]],
            Some(&[
                "pipeline/gate_consumer_sim.go", "pipeline/tw.go", "pipeline/gates_test.go",
                "dist/css/**", "dist/shadless-core.css", "package.json", "node_modules/.bin/tailwindcss",
            ]),
            None,
            "the PRIMARY consume path, machine-checked: a scratch consumer importing core + N component files gets exactly those styles, and every component compiles ALONE (not only as part of the full product entry)",
            &["consumer-sim-unknown-utility"],
        ),
        node(
            "path-parity", "gate", "full",
            &["product-build", "oracle-css", "build-js"],
            &[&["./build/pipeline", "path-parity"]],
            Some(&[
                "pipeline/path_parity.go", "pipeline/pp_readall.js", "pipeline/parity_baseline.go",
                "pipeline/emitter_css.go", "pipeline/tags.go", "pipeline/browser_shell.go",
                "tools/browser-shell.mjs", "gates/path-parity-baseline.json", "gates/ledger.json",
                "src/emitter/skin.mjs", "generated/ir/**", "dist/css/**", "dist/shadless.full.css",
                "build/gates/oracle.css", "src/registry/pin.json",
            ]),
            None,
            "for EVERY slot, slot-only markup via css-import and via full.css must compute what React's inline classes compute under upstream's own stylesheet, in both themes and directions, at rest, per cva variant value and per attribute-driven state, with referenced child slots rendered on both sides — subsumes the retired variant-parity; found cva defaults living in fn params (attachment, marker), toggle's pressed state losing to the (0,2,0) variant qualifier, and twMerge residue (text-sm line-height)",
            &["path-parity-drop-utility", "variant-merge-defaults"],
        ),
        node(
            "demo-parity", "gate", "full",
            &["demo-css", "oracle-css", "example-oracle", "build-js"],
            &[&["./build/pipeline", "demo-parity"]],
            Some(&[
                "pipeline/demo_parity.go", "pipeline/demo_parity_collect.js", "pipeline/parity_baseline.go",
                "pipeline/browser_shell.go", "tools/browser-shell.mjs", "gates/demo-parity-baseline.json",
                "gates/ledger.json", "build/gates/oracle.css", "dist/out.css", "docs/demos/**",
                "docs/example-oracle.json",
            ]),
            None,
            "every shipped demo page's DOM under our css must compute what the SAME DOM computes under upstream's stylesheet, light/dark x ltr/rtl — same DOM on both sides, so every cell is emitted css (skin markers, slot rules leaking under inline utilities, tokens)",
            &["demo-parity-token-drift"],
        ),
        node(
            "css-direction", "gate", "fast",
            &["demo-css"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestCssDirection", "."]],
            Some(&["pipeline/gate_css_direction.go", "pipeline/gate_css_direction_test.go", "pipeline/gates_test.go", "dist/shadless.css"]),
            None,
            "emitted physical reading-direction utilities must match the recorded set — new/gone entries mean upstream moved the RTL story",
            &["css-direction-new-physical"],
        ),
        node(
            "contracts", "gate", "full",
            &["demo-css"],
            &[&["./build/pipeline", "contracts"]],
            Some(&[
                "pipeline/contract.go", "pipeline/oracle_lib.go", "pipeline/resolve_skins.go",
                "pipeline/browser_shell.go", "tools/browser-shell.mjs", "tools/contracts/stubs/**",
                "tools/contracts/components/**", "dist/**", "src/kernel/**", "src/registry/pin.json",
                "package-lock.json", "gates/ledger.json",
            ]),
            Some(&["tools/contracts/out"]),
            "THE oracle: the pinned registry bundled with real React+radix, replayed against the shipped pages with real mouse/keyboard, incl. mounted-DOM structure",
            &["contracts-strip-glue"],
        ),
        node(
            "oracle-css", "build", "full",
            &["convert"],
            &[&["./build/pipeline", "oracle-css"]],
            Some(&[
                "pipeline/oracle_css.go", "pipeline/tw.go", "pipeline/main.go", "src/registry/pin.json",
                "build/resolved-ui/**", ".upstream/shadcn-ui/apps/v4/app/legacy-themes.css",
                ".upstream/shadcn-ui/apps/v4/package.json", "package.json",
            ]),
            Some(&["build/gates/oracle.css"]),
            "a stylesheet for the React oracle built from upstream's own globals/skin and the resolved registry — reads nothing under src/, so style-parity is no longer circular",
            &[],
        ),
        node(
            "style-parity", "gate", "full",
            &["contracts", "oracle-css", "build-js"],
            &[&["./build/pipeline", "style-parity"]],
            Some(&[
                "pipeline/style_parity.go", "pipeline/parity_baseline.go", "pipeline/browser_shell.go",
                "tools/browser-shell.mjs", "gates/style-parity-baseline.json", "gates/ledger.json",
                "tools/contracts/out/**", "tools/contracts/components/**", "build/gates/oracle.css",
                "src/registry/pin.json",
            ]),
            None,
            "computed STYLE parity vs the React oracle — 'same DOM + same css => same styles' was an inference no gate ever tested",
            &["style-parity-perturb-padding", "style-parity-recorded-value-drift"],
        ),
        node(
            "demo-smoke", "gate", "full",
            &["demo-css", "build-js"],
            &[&["./build/pipeline", "demo-smoke"]],
            Some(&[
                "pipeline/demo_smoke.go", "pipeline/browser_shell.go", "tools/browser-shell.mjs",
                "dist/**", "generated/ir/**", "src/registry/tiers.json",
            ]),
            None,
            "every dist demo page loads with zero console errors",
            &["demo-smoke-console-error"],
        ),
        node(
            "docs-catalog", "build", "full",
            &["demo"],
            &[&["./build/pipeline", "docs-catalog"]],
            Some(&[
                "pipeline/docs_catalog.go", "pipeline/jsonorder.go", "pipeline/main.go",
                "src/registry/pin.json", "src/registry/tiers.json", "dist/components/**", "docs/demos/**",
            ]),
            Some(&["docs/catalog.json"]),
            "the preview catalog the site is generated from",
            &[],
        ),
        node(
            "docs-upstream-mirror", "build", "fast",
            &["pin"],
            &[&["./build/pipeline", "docs-upstream-mirror"]],
            Some(&["pipeline/docs_upstream_mirror.go", "src/registry/pin.json", UPSTREAM_DOCS_GLOB]),
            Some(&[DOCS_UPSTREAM_MIRROR]),
            "a tracked, git-diffable copy of the upstream docs .mdx docs-build/docs-fidelity read and docs_overrides.go hand-patches — the analogue of generated/ir for the docs pipeline (pipeline/convert.go's registry .tsx -> versioned IR), so a re-pin's content change shows up as a normal git diff in this repo instead of only a build-time anchor failure",
            &[],
        ),
        node(
            "docs-build", "build", "full",
            &["docs-catalog", "docs-upstream-mirror", "demo-css", "build-js"],
            &[&["./build/pipeline", "docs-build"]],
            Some(&[
                "pipeline/docs_build.go", "pipeline/docs_guides.go", "pipeline/docs_transforms.go",
                "pipeline/docs_overrides.go", "pipeline/docs_frontmatter.go", "pipeline/docs_scripts.go",
                "pipeline/docs_families.go", "pipeline/docs_fidelity.go", "tools/prettier-batch.mjs",
                "docs/catalog.json", "docs/content/**", "dist/**", "docs/demos/**",
                "build/rtl-langs.json", "generated/ir/**", "src/registry/pin.json", "package.json",
                "package-lock.json", "generated/docs-upstream/**",
            ]),
            Some(&["docs/site/content", "docs/site/static", "docs/content-map.json"]),
            "mdx -> the mirrored site, with the dist demos copied in under the site skin",
            &[],
        ),
        node(
            "docs-site", "build", "full",
            &["docs-build"],
            &[&["zola", "--root", "docs/site", "build"]],
            Some(&[
                "docs/site/content/**", "docs/site/static/**", "docs/site/config.toml",
                "docs/site/templates/**", "docs/site/sass/**", "docs/site/themes/**",
            ]),
            Some(&["docs/site/public"]),
            "the markdown becomes a site, and a link to a page this mirror does not carry stops the build",
            &[],
        ),
        node(
            "docs-consistency", "gate", "fast",
            &["docs-build", "build-js"],
            &[&["./build/pipeline", "docs-consistency"]],
            Some(&[
                "pipeline/docs_consistency.go", "pipeline/resolve_skins.go", "docs/site/content/**",
                "dist/components/**", "dist/css/**", "docs/demos/**", "package.json",
            ]),
            None,
            "no shipped page carries skin residue, every taught @import resolves to a file, and no page teaches React imports",
            &["docs-consistency-react-import"],
        ),
        node(
            "docs-fidelity", "gate", "fast",
            &["docs-build", "build-js"],
            &[&["./build/pipeline", "docs-fidelity"]],
            Some(&[
                "pipeline/docs_fidelity_driver.go", "pipeline/docs_fidelity.go",
                "pipeline/docs_transforms.go", "pipeline/docs_overrides.go", "pipeline/docs_guides.go",
                "pipeline/docs_frontmatter.go", "docs/site/content/**", "docs/site/static/demos/**",
                "docs/content-map.json", "docs/content/**", "src/registry/pin.json",
                "generated/docs-upstream/**",
            ]),
            None,
            "every built page matches its mdx source (headings/TOC/previews/fences) — catches silent content loss that render and console checks cannot see",
            &["docs-fidelity-drop-heading"],
        ),
        node(
            "docs-smoke", "gate", "full",
            &["docs-site", "build-js"],
            &[&["./build/pipeline", "docs-smoke", "--all"]],
            Some(&["pipeline/docs_smoke.go", "pipeline/browser_shell.go", "tools/browser-shell.mjs", "docs/site/public/**"]),
            None,
            "every page and every iframe loads with zero console/page errors",
            &["docs-smoke-broken-iframe"],
        ),
        node(
            "interactivity-sweep", "gate", "full",
            &["docs-build", "build-js"],
            &[&["./build/pipeline", "interactivity-sweep"]],
            Some(&[
                "pipeline/interactivity_sweep.go", "pipeline/browser_shell.go", "tools/browser-shell.mjs",
                "docs/site/static/demos/**", "src/registry/tiers.json", "gates/ledger.json",
            ]),
            None,
            "every page that OFFERS an interaction must RESPOND — contracts click fixtures, golden compares snapshots, smoke listens to the console; the dead-button bug lived in exactly that responsibility gap",
            &["interactivity-strip-script"],
        ),
        node(
            "reproducible", "gate", "full",
            &["docs-build", "product-build", "demo-rtl", "example-fixture"],
            &[&["go", "test", "-C", "pipeline", "-count=1", "-v", "-run", "^TestReproducible$", "."]],
            None, // judges state outside the tree: never fresh
            None,
            "the committed generated trees must equal a fresh pipeline run — the only authority on hand-edited outputs, replacing the pre-commit hook's guesswork",
            &["reproducible-hand-edit"],
        ),
        node(
            "golden-gate", "gate", "full",
            &["example-oracle", "build-js"],
            &[&["./build/pipeline", "example-golden"]],
            Some(&[
                "pipeline/example_golden.go", "pipeline/oracle_lib.go", "pipeline/resolve_skins.go",
                "pipeline/oracle_canon.js", "pipeline/browser_shell.go", "tools/browser-shell.mjs",
                "src/registry/upstream-snapshot/**", "gates/ledger.json", "tools/contracts/stubs/**",
                "src/emitter/skin.mjs", "src/registry/pin.json", "package-lock.json",
                UPSTREAM_EXAMPLES_GLOB,
            ]),
            None,
            "hop 1 — the local React oracle render must equal the committed ui.shadcn.com snapshot",
            &["golden-perturb-oracle"],
        ),
        node(
            "example-gate", "gate", "full",
            &["docs-build", "build-js"],
            &[&["./build/pipeline", "example-oracle", "--check"]],
            Some(&[
                "pipeline/example_oracle.go", "pipeline/oracle_lib.go", "pipeline/oracle_canon.js",
                "pipeline/browser_shell.go", "tools/browser-shell.mjs", "docs/demos/**",
                "docs/example-oracle.json", "src/registry/tiers.json", "tools/contracts/stubs/**",
                "src/emitter/skin.mjs", "src/registry/pin.json", "package-lock.json",
                UPSTREAM_EXAMPLES_GLOB,
            ]),
            None,
            "hop 2 — each shipped demo page must equal a fresh oracle render. hop1 + hop2 together prove shipped == React == live",
            &["example-perturb-shipped"],
        ),
    ]
}
